<?php
// ================================================================
//  portal/index.php  — Client Portal (Public, No Login Required)
//  URL: https://invcs.optms.co.in/portal?t=TOKEN
//
//  TOKEN format: base64(invoiceId + ':' + invoiceNumber)
//  e.g. btoa("81:INV-2026-002") = "ODE6SU5WLTIwMjYtMDAy"
//
//  No DB token table needed — the invoice ID is embedded in the
//  base64 token itself (generated by the frontend _portalURL fn).
// ================================================================

require_once __DIR__ . '/../config/db.php';

$rawToken = $_GET['t'] ?? '';
$error    = '';
$inv      = null;
$client   = [];
$payments = [];
$settings = [];
$invoiceId = 0;

if (!$rawToken) {
    $error = 'Invalid or missing link. Please ask your service provider for a valid invoice link.';
} else {
    // ── Detect token format ──────────────────────────────────────
    // Format A: 32-char lowercase hex  → random token stored in portal_tokens table
    //           e.g. "8bf863a1605406e45d14b80eebe5c846"
    // Format B: base64(id:invoiceNum)  → btoa token generated by frontend _portalURL()
    //           e.g. "ODE6SU5WLTIwMjYtMDAy" decodes to "81:INV-2026-002"

    if (preg_match('/^[0-9a-f]{32}$/', $rawToken)) {
        // ── Format A: hex token — look up in portal_tokens DB ────
        try {
            $db = getDB();

            // Auto-create table if needed
            $db->exec("CREATE TABLE IF NOT EXISTS `portal_tokens` (
                `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
                `invoice_id`  INT UNSIGNED NOT NULL,
                `token`       VARCHAR(64)  NOT NULL,
                `views`       INT UNSIGNED NOT NULL DEFAULT 0,
                `last_viewed` DATETIME     NULL,
                `expires_at`  DATETIME     NULL,
                `created_at`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_portal_invoice` (`invoice_id`),
                UNIQUE KEY `uk_portal_token`   (`token`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            $stmt = $db->prepare(
                'SELECT invoice_id FROM portal_tokens
                 WHERE token = :token
                   AND (expires_at IS NULL OR expires_at > NOW())
                 LIMIT 1'
            );
            $stmt->execute([':token' => $rawToken]);
            $row = $stmt->fetch(PDO::FETCH_ASSOC);
            if ($row) {
                $invoiceId = (int)$row['invoice_id'];
                // Bump view counter
                $db->prepare('UPDATE portal_tokens SET views = views + 1, last_viewed = NOW() WHERE token = :t')
                   ->execute([':t' => $rawToken]);
            } else {
                $error = 'This link is invalid or has expired. Please contact your service provider.';
            }
        } catch (Exception $e) {
            error_log('portal hex token lookup error: ' . $e->getMessage());
            $error = 'A server error occurred. Please try again later.';
        }

    } else {
        // ── Format B: base64(id:num) token — decode directly ─────
        $decoded = base64_decode(strtr($rawToken, '-_', '+/'), true);
        if ($decoded === false || strpos($decoded, ':') === false) {
            $error = 'Invalid link format. Please ask your service provider for a valid link.';
        } else {
            // "81:INV-2026-002" → invoice ID is the part before ':'
            $parts     = explode(':', $decoded, 2);
            $invoiceId = (int)$parts[0];
            if ($invoiceId <= 0) {
                $error = 'Invalid link. Invoice ID could not be determined.';
            }
        }
    }
}

if (!$error && $invoiceId > 0) {
    try {
        $db = getDB();

        // Fetch invoice — look up by id only (the number in the token is just for display)
        $stmt = $db->prepare("
            SELECT i.id AS invoice_id, i.invoice_number, i.issued_date AS issue_date,
                   i.due_date, i.grand_total AS amount, i.subtotal,
                   i.discount_pct, i.discount_amt, i.gst_amount,
                   i.status, i.client_id, i.service_type,
                   i.notes, i.terms, i.bank_details, i.currency
            FROM invoices i WHERE i.id = :id LIMIT 1
          ");
        $stmt->execute([':id' => $invoiceId]);
        $inv = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$inv) {
            $error = 'Invoice not found. The link may be outdated.';
        } else {
            // Client details
            $cStmt = $db->prepare(
                'SELECT name, email, phone, address FROM clients WHERE id = :id'
            );
            $cStmt->execute([':id' => $inv['client_id']]);
            $client = $cStmt->fetch(PDO::FETCH_ASSOC) ?: [];

            // Payment history
            $pStmt = $db->prepare(
                'SELECT amount, payment_date, method, transaction_id, notes
                 FROM payments WHERE invoice_id = :id ORDER BY payment_date ASC'
            );
            $pStmt->execute([':id' => $inv['invoice_id']]);
            $payments = $pStmt->fetchAll(PDO::FETCH_ASSOC);

            // Company settings
            try {
                $sRows = $db->query("SELECT `key`, value FROM settings")->fetchAll(PDO::FETCH_ASSOC);
                foreach ($sRows as $r) $settings[$r['key']] = $r['value'];
            } catch (Exception $e) { /* settings table might differ */ }
        }
    } catch (Exception $e) {
        error_log('portal/index.php error: ' . $e->getMessage());
        $error = 'A server error occurred. Please try again later.';
    }
}

// ── Helpers ──────────────────────────────────────────────────
function fmt_inr($n, $sym = '₹') {
    return $sym . number_format((float)$n, 2, '.', ',');
}
function status_col($s) {
    return match($s) {
        'Paid'      => '#388E3C',
        'Pending'   => '#F9A825',
        'Overdue'   => '#C62828',
        'Partial'   => '#E65100',
        'Draft'     => '#9E9E9E',
        'Cancelled' => '#757575',
        default     => '#888'
    };
}

$sym        = $inv['currency'] ?: '₹';
$totalAmt   = (float)($inv['amount']  ?? 0);
$totalPaid  = array_sum(array_column($payments, 'amount'));
$remaining  = max(0, $totalAmt - $totalPaid);
$pct        = $totalAmt > 0 ? min(100, round($totalPaid / $totalAmt * 100)) : 0;

$companyName    = $settings['company_name']    ?? 'OPTMS Tech';
$companyAddress = $settings['company_address'] ?? '';
$companyGST     = $settings['company_gst']     ?? '';
$companyEmail   = $settings['company_email']   ?? '';
$companyPhone   = $settings['company_phone']   ?? '';
$companyUPI     = $settings['company_upi']     ?? '';
$companyQR      = $settings['company_qr']      ?? '';
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Invoice <?= htmlspecialchars($inv['invoice_number'] ?? '') ?> — <?= htmlspecialchars($companyName) ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --teal:#00897B;--teal-bg:#E0F2F1;
  --green:#388E3C;--green-bg:#E8F5E9;
  --amber:#F9A825;--red:#C62828;--red-bg:#FFEBEE;--orange:#E65100;
  --muted:#6B7280;--border:#E5E7EB;--card:#fff;--bg:#F5F6FA;--text:#1A1A2E;
  --mono:'JetBrains Mono',monospace;--font:'Public Sans',-apple-system,sans-serif;
}
html{font-size:15px;background:var(--bg)}
body{font-family:var(--font);color:var(--text);min-height:100vh;padding:20px 16px 60px}
.wrap{max-width:700px;margin:0 auto}

.portal-header{background:linear-gradient(135deg,var(--teal),#00695C);border-radius:14px;padding:20px 24px;color:#fff;margin-bottom:20px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px}
.brand-logo{width:42px;height:42px;border-radius:10px;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center;font-size:18px;font-weight:800;color:#fff;flex-shrink:0}
.brand-name{font-size:16px;font-weight:800}
.brand-sub{font-size:11px;opacity:.75;margin-top:2px}
.inv-num{font-size:18px;font-weight:800;font-family:var(--mono)}
.status-pill{display:inline-flex;align-items:center;gap:5px;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;background:rgba(255,255,255,.2);border:1px solid rgba(255,255,255,.3);margin-top:4px}

.card{background:var(--card);border-radius:12px;border:1px solid var(--border);box-shadow:0 1px 4px rgba(0,0,0,.06);margin-bottom:16px}
.card-head{padding:13px 18px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:8px;font-size:13px;font-weight:700}
.card-head i{color:var(--teal);font-size:12px}
.card-body{padding:16px 18px}

.amount-strip{display:grid;grid-template-columns:1fr 1fr 1fr;gap:1px;background:var(--border);border-radius:0 0 12px 12px;overflow:hidden}
.amt-cell{background:var(--card);padding:14px;text-align:center}
.amt-cell .lbl{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:var(--muted);margin-bottom:4px}
.amt-cell .val{font-size:16px;font-weight:800;font-family:var(--mono)}

.progress-wrap{padding:10px 18px 14px;background:var(--bg);border-top:1px solid var(--border)}
.progress-bar{height:7px;background:#E5E7EB;border-radius:4px;overflow:hidden;margin-bottom:5px}
.progress-fill{height:100%;background:linear-gradient(90deg,#43A047,#66BB6A);border-radius:4px;transition:width .5s ease}
.progress-meta{display:flex;justify-content:space-between;font-size:11px;color:var(--muted)}

.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}
.info-item label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:var(--muted);display:block;margin-bottom:3px}
.info-item .val{font-size:13px;font-weight:600}

table{width:100%;border-collapse:collapse;font-size:13px}
th{padding:9px 12px;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);background:var(--bg);border-bottom:2px solid var(--border);text-align:left}
th.r,td.r{text-align:right}
td{padding:9px 12px;border-bottom:1px solid var(--border)}
tr:last-child td{border:none}

.pmt-row{display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--border)}
.pmt-row:last-child{border:none}
.pmt-ic{width:32px;height:32px;border-radius:8px;background:var(--green-bg);color:var(--green);display:flex;align-items:center;justify-content:center;flex-shrink:0}
.pmt-info{flex:1;min-width:0}
.pmt-method{font-weight:600;font-size:12px}
.pmt-date{font-size:11px;color:var(--muted);margin-top:1px}
.pmt-txn{font-size:10px;color:var(--muted);font-family:var(--mono);margin-top:1px}
.pmt-amt{font-family:var(--mono);font-weight:700;color:var(--green);font-size:14px}

.upi-box{background:var(--teal-bg);border-radius:10px;padding:13px 16px;display:flex;align-items:center;gap:12px}
.upi-ic{width:36px;height:36px;border-radius:8px;background:var(--teal);color:#fff;display:flex;align-items:center;justify-content:center;font-size:15px;flex-shrink:0}
.upi-id{font-family:var(--mono);font-size:14px;font-weight:700;color:var(--teal)}
.copy-btn{margin-left:auto;padding:6px 14px;background:var(--teal);color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:12px;font-weight:600;font-family:var(--font);white-space:nowrap}
.copy-btn:hover{background:#00695C}

.footer{text-align:center;margin-top:24px;font-size:11px;color:var(--muted);line-height:1.9}
.error-box{background:#fff;border-radius:14px;border:2px solid #FFCDD2;padding:48px 32px;text-align:center;max-width:460px;margin:80px auto;box-shadow:0 4px 24px rgba(0,0,0,.08)}

@media(max-width:520px){
  .portal-header{flex-direction:column;align-items:flex-start}
  .info-grid{grid-template-columns:1fr}
  .amount-strip{grid-template-columns:1fr}
}
</style>
</head>
<body>
<div class="wrap">

<?php if ($error): ?>
<div class="error-box">
  <i class="fas fa-link-slash" style="font-size:44px;color:#FFCDD2;display:block;margin-bottom:18px"></i>
  <h2 style="font-size:18px;margin-bottom:10px">Link Unavailable</h2>
  <p style="color:var(--muted);font-size:13px;line-height:1.7"><?= htmlspecialchars($error) ?></p>
  <div style="margin-top:24px;font-size:12px;color:var(--muted)">
    Powered by <strong><?= htmlspecialchars($companyName) ?></strong>
  </div>
</div>
<?php else: ?>

<!-- Header -->
<div class="portal-header">
  <div style="display:flex;align-items:center;gap:12px">
    <div class="brand-logo"><?= strtoupper(substr($companyName,0,2)) ?></div>
    <div>
      <div class="brand-name"><?= htmlspecialchars($companyName) ?></div>
      <?php if ($companyAddress): ?>
      <div class="brand-sub"><?= htmlspecialchars($companyAddress) ?></div>
      <?php endif; ?>
    </div>
  </div>
  <div style="text-align:right">
    <div class="inv-num"><?= htmlspecialchars($inv['invoice_number'] ?? '') ?></div>
    <div class="status-pill">
      <span style="width:6px;height:6px;border-radius:50%;background:<?= status_col($inv['status'] ?? '') ?>"></span>
      <?= htmlspecialchars($inv['status'] ?? '') ?>
    </div>
  </div>
</div>

<!-- Amount summary -->
<div class="card">
  <div class="amount-strip" style="border-radius:12px 12px 0 0">
    <div class="amt-cell">
      <div class="lbl">Invoice Total</div>
      <div class="val" style="color:var(--teal)"><?= fmt_inr($totalAmt, $sym) ?></div>
    </div>
    <div class="amt-cell">
      <div class="lbl">Amount Paid</div>
      <div class="val" style="color:var(--green)"><?= fmt_inr($totalPaid, $sym) ?></div>
    </div>
    <div class="amt-cell">
      <div class="lbl"><?= $remaining > 0 ? 'Balance Due' : 'Status' ?></div>
      <div class="val" style="color:<?= $remaining > 0 ? 'var(--red)' : 'var(--green)' ?>">
        <?= $remaining > 0 ? fmt_inr($remaining, $sym) : '✓ Cleared' ?>
      </div>
    </div>
  </div>
  <?php if ($totalAmt > 0): ?>
  <div class="progress-wrap">
    <div class="progress-bar"><div class="progress-fill" style="width:<?= $pct ?>%"></div></div>
    <div class="progress-meta">
      <span><?= $pct ?>% paid</span>
      <span><?= count($payments) ?> payment<?= count($payments) !== 1 ? 's' : '' ?></span>
    </div>
  </div>
  <?php endif; ?>
</div>

<!-- Invoice details -->
<div class="card">
  <div class="card-head"><i class="fas fa-file-invoice"></i> Invoice Details</div>
  <div class="card-body">
    <div class="info-grid">
      <div class="info-item"><label>Invoice #</label><span class="val" style="font-family:var(--mono)"><?= htmlspecialchars($inv['invoice_number'] ?? '') ?></span></div>
      <div class="info-item"><label>Service</label><span class="val"><?= htmlspecialchars($inv['service_type'] ?? '—') ?></span></div>
      <div class="info-item"><label>Issue Date</label><span class="val"><?= htmlspecialchars($inv['issue_date'] ?? '—') ?></span></div>
      <div class="info-item"><label>Due Date</label>
        <span class="val" style="color:<?= $inv['status']==='Overdue' ? 'var(--red)' : 'inherit' ?>">
          <?= htmlspecialchars($inv['due_date'] ?? '—') ?>
          <?php if ($inv['status']==='Overdue'): ?> <i class="fas fa-exclamation-triangle" style="color:var(--red);font-size:11px"></i><?php endif; ?>
        </span>
      </div>
      <?php if (!empty($inv['gst_rate'])): ?>
      <div class="info-item"><label>GST Rate</label><span class="val"><?= htmlspecialchars($inv['gst_rate']) ?>%</span></div>
      <?php endif; ?>
      <?php if (!empty($inv['discount']) && $inv['discount'] != '0' && $inv['discount'] != '0.00'): ?>
      <div class="info-item"><label>Discount</label><span class="val"><?= htmlspecialchars($inv['discount']) ?></span></div>
      <?php endif; ?>
    </div>
  </div>
</div>

<!-- Client info -->
<?php if ($client && !empty($client['name'])): ?>
<div class="card">
  <div class="card-head"><i class="fas fa-user"></i> Billed To</div>
  <div class="card-body">
    <div class="info-grid">
      <div class="info-item"><label>Name</label><span class="val"><?= htmlspecialchars($client['name']) ?></span></div>
      <?php if (!empty($client['email'])): ?><div class="info-item"><label>Email</label><span class="val"><?= htmlspecialchars($client['email']) ?></span></div><?php endif; ?>
      <?php if (!empty($client['phone'])): ?><div class="info-item"><label>Phone</label><span class="val"><?= htmlspecialchars($client['phone']) ?></span></div><?php endif; ?>
      <?php if (!empty($client['address'])): ?><div class="info-item" style="grid-column:1/-1"><label>Address</label><span class="val" style="font-weight:400"><?= nl2br(htmlspecialchars($client['address'])) ?></span></div><?php endif; ?>
    </div>
  </div>
</div>
<?php endif; ?>

<!-- Line items -->
<?php
$iStmt = $db->prepare('SELECT description AS name, quantity AS qty, rate, gst_rate AS gst, line_total AS total FROM invoice_items WHERE invoice_id = :id ORDER BY sort_order ASC');
$iStmt->execute([':id' => $inv['invoice_id']]);
$items = $iStmt->fetchAll(PDO::FETCH_ASSOC);
if ($items):
?>
<div class="card">
  <div class="card-head"><i class="fas fa-list-ul"></i> Line Items</div>
  <table>
    <thead><tr>
      <th>#</th><th>Description</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th><th class="r">GST</th><th class="r">Total</th>
    </tr></thead>
    <tbody>
    <?php foreach ($items as $i => $item): ?>
    <tr>
      <td style="color:var(--muted);font-size:12px"><?= $i+1 ?></td>
      <td>
        <strong><?= htmlspecialchars($item['name'] ?? $item['desc'] ?? '') ?></strong>
        <?php if (!empty($item['type'])): ?><br><span style="font-size:11px;color:var(--muted)"><?= htmlspecialchars($item['type']) ?></span><?php endif; ?>
      </td>
      <td class="r"><?= htmlspecialchars((string)($item['qty'] ?? 1)) ?></td>
      <td class="r" style="font-family:var(--mono)"><?= fmt_inr($item['rate'] ?? 0, '') ?></td>
      <td class="r" style="font-family:var(--mono)"><?= fmt_inr((float)($item['qty'] ?? 1) * (float)($item['rate'] ?? 0), '') ?></td>
      <td class="r"><?= htmlspecialchars((string)($item['gst'] ?? 0)) ?>%</td>
      <td class="r" style="font-family:var(--mono);font-weight:700"><?= fmt_inr($item['total'] ?? $item['amount'] ?? 0, $sym) ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
      <tr style="background:var(--bg)">
        <td colspan="6" style="text-align:right;font-weight:700;padding:11px 12px;font-size:13px">Grand Total</td>
        <td class="r" style="font-family:var(--mono);font-size:16px;font-weight:800;color:var(--teal);padding:11px 12px"><?= fmt_inr($totalAmt, $sym) ?></td>
      </tr>
    </tfoot>
  </table>
</div>
<?php endif; ?>

<!-- Payment history -->
<?php if ($payments): ?>
<div class="card">
  <div class="card-head"><i class="fas fa-receipt"></i> Payment History</div>
  <div class="card-body" style="padding:0 18px">
    <?php foreach ($payments as $p): ?>
    <div class="pmt-row">
      <div class="pmt-ic"><i class="fas fa-check"></i></div>
      <div class="pmt-info">
        <div class="pmt-method"><?= htmlspecialchars($p['method'] ?? 'Payment') ?></div>
        <div class="pmt-date"><?= htmlspecialchars($p['payment_date'] ?? '') ?></div>
        <?php if (!empty($p['transaction_id'])): ?>
        <div class="pmt-txn">Ref: <?= htmlspecialchars($p['transaction_id']) ?></div>
        <?php endif; ?>
        <?php if (!empty($p['notes'])): ?>
        <div class="pmt-txn"><?= htmlspecialchars($p['notes']) ?></div>
        <?php endif; ?>
      </div>
      <div class="pmt-amt"><?= fmt_inr($p['amount'], $sym) ?></div>
    </div>
    <?php endforeach; ?>
  </div>
</div>
<?php endif; ?>

<!-- Pay now (only if balance due) -->
<?php if ($remaining > 0.01 && $companyUPI): ?>
<div class="card">
  <div class="card-head"><i class="fas fa-mobile-alt"></i> Pay Now</div>
  <div class="card-body">
    <p style="font-size:12px;color:var(--muted);margin-bottom:12px">
      Pay the remaining <strong style="color:var(--red)"><?= fmt_inr($remaining, $sym) ?></strong> via UPI:
    </p>
    <div class="upi-box">
      <div class="upi-ic"><i class="fas fa-rupee-sign"></i></div>
      <div>
        <div style="font-size:9px;font-weight:700;text-transform:uppercase;color:var(--muted);margin-bottom:2px">UPI ID</div>
        <div class="upi-id" id="upiId"><?= htmlspecialchars($companyUPI) ?></div>
      </div>
      <button class="copy-btn" onclick="copyUPI()" id="copyBtn"><i class="fas fa-copy"></i> Copy</button>
    </div>
    <?php if ($companyQR): ?>
    <div style="text-align:center;margin-top:14px">
      <img src="<?= htmlspecialchars($companyQR) ?>" alt="QR Code" style="width:150px;height:150px;border-radius:10px;border:1px solid var(--border)">
      <div style="font-size:11px;color:var(--muted);margin-top:6px">Scan & Pay</div>
    </div>
    <?php endif; ?>
  </div>
</div>
<?php endif; ?>

<!-- Notes & T&C -->
<?php if (!empty($inv['notes']) || !empty($inv['terms']) || !empty($inv['bank_details'])): ?>
<div class="card">
  <div class="card-head"><i class="fas fa-sticky-note"></i> Notes & Terms</div>
  <div class="card-body" style="display:flex;flex-direction:column;gap:14px">
    <?php if (!empty($inv['notes'])): ?>
    <div>
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);margin-bottom:5px">Notes</div>
      <div style="font-size:13px;line-height:1.6"><?= nl2br(htmlspecialchars($inv['notes'])) ?></div>
    </div>
    <?php endif; ?>
    <?php if (!empty($inv['bank_details'])): ?>
    <div>
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);margin-bottom:5px">Bank Details</div>
      <div style="font-size:13px;line-height:1.6;font-family:var(--mono)"><?= nl2br(htmlspecialchars($inv['bank_details'])) ?></div>
    </div>
    <?php endif; ?>
    <?php if (!empty($inv['terms'])): ?>
    <div>
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);margin-bottom:5px">Terms & Conditions</div>
      <div style="font-size:12px;color:var(--muted);line-height:1.7"><?= nl2br(htmlspecialchars($inv['terms'])) ?></div>
    </div>
    <?php endif; ?>
  </div>
</div>
<?php endif; ?>

<!-- Company footer -->
<div class="card">
  <div class="card-head"><i class="fas fa-building"></i> Issued By</div>
  <div class="card-body">
    <div class="info-grid">
      <div class="info-item"><label>Company</label><span class="val"><?= htmlspecialchars($companyName) ?></span></div>
      <?php if ($companyGST): ?><div class="info-item"><label>GSTIN</label><span class="val" style="font-family:var(--mono)"><?= htmlspecialchars($companyGST) ?></span></div><?php endif; ?>
      <?php if ($companyPhone): ?><div class="info-item"><label>Phone</label><span class="val"><?= htmlspecialchars($companyPhone) ?></span></div><?php endif; ?>
      <?php if ($companyEmail): ?><div class="info-item"><label>Email</label><span class="val"><?= htmlspecialchars($companyEmail) ?></span></div><?php endif; ?>
      <?php if ($companyAddress): ?><div class="info-item" style="grid-column:1/-1"><label>Address</label><span class="val" style="font-weight:400"><?= nl2br(htmlspecialchars($companyAddress)) ?></span></div><?php endif; ?>
    </div>
  </div>
</div>

<div class="footer">
  <div>This is a secure, read-only view of your invoice.</div>
  <div>Generated by <strong><?= htmlspecialchars($companyName) ?></strong> · Powered by OPTMS Invoice Manager</div>
</div>

<?php endif; ?>
</div>

<script>
function copyUPI() {
  const id  = document.getElementById('upiId')?.textContent?.trim();
  const btn = document.getElementById('copyBtn');
  if (!id) return;
  const done = () => {
    if (btn) { btn.innerHTML='<i class="fas fa-check"></i> Copied!'; btn.style.background='#388E3C'; }
    setTimeout(()=>{ if(btn){btn.innerHTML='<i class="fas fa-copy"></i> Copy';btn.style.background='';} }, 2000);
  };
  if (navigator.clipboard) {
    navigator.clipboard.writeText(id).then(done).catch(()=>fallback(id,done));
  } else { fallback(id,done); }
}
function fallback(text,cb) {
  const ta=document.createElement('textarea'); ta.value=text; ta.style.position='fixed'; ta.style.opacity='0';
  document.body.appendChild(ta); ta.focus(); ta.select(); try{document.execCommand('copy');}catch(e){}
  document.body.removeChild(ta); cb();
}
</script>
</body>
</html>