<?php
// ================================================================
//  portal/index.php  — Client Portal (Public, No Login Required)
//  URL: https://invcs.optms.co.in/portal?t=TOKEN
//
//  TOKEN format: base64(invoiceId + ':' + invoiceNumber)
//  e.g. btoa("81:INV-2026-002") = "ODE6SU5WLTIwMjYtMDAy"
//
//  No DB token table needed — the invoice ID is embedded in the
//  base64 token itself (generated by the frontend _portalURL fn).
// ================================================================

require_once __DIR__ . '/../config/db.php';

$rawToken = $_GET['t'] ?? '';
$error    = '';
$inv      = null;
$client   = [];
$payments = [];
$settings = [];
$invoiceId = 0;

$firstViewed = null;
$viewCount   = null;

if (!$rawToken) {
    $error = 'Invalid or missing link. Please ask your service provider for a valid invoice link.';
} else {
    // ── Detect token format ──────────────────────────────────────
    // Format A: 32-char lowercase hex  → random token stored in portal_tokens table
    //           e.g. "8bf863a1605406e45d14b80eebe5c846"
    // Format B: base64(id:invoiceNum)  → btoa token generated by frontend _portalURL()
    //           e.g. "ODE6SU5WLTIwMjYtMDAy" decodes to "81:INV-2026-002"

    if (preg_match('/^[0-9a-f]{32}$/', $rawToken)) {
        // ── Format A: hex token — look up in portal_tokens DB ────
        try {
            $db = getDB();

            // Auto-create table if needed
            $db->exec("CREATE TABLE IF NOT EXISTS `portal_tokens` (
                `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
                `invoice_id`  INT UNSIGNED NOT NULL,
                `token`       VARCHAR(64)  NOT NULL,
                `views`       INT UNSIGNED NOT NULL DEFAULT 0,
                `last_viewed` DATETIME     NULL,
                `expires_at`  DATETIME     NULL,
                `created_at`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_portal_invoice` (`invoice_id`),
                UNIQUE KEY `uk_portal_token`   (`token`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            $stmt = $db->prepare(
                'SELECT invoice_id, first_viewed, view_count, views FROM portal_tokens
                 WHERE token = :token
                   AND (expires_at IS NULL OR expires_at > NOW())
                 LIMIT 1'
            );
            $stmt->execute([':token' => $rawToken]);
            $row = $stmt->fetch(PDO::FETCH_ASSOC);
            if ($row) {
                $invoiceId  = (int)$row['invoice_id'];
                $firstViewed = $row['first_viewed'];
                $viewCount   = (int)($row['view_count'] ?? $row['views'] ?? 0) + 1;
                // Set first_viewed on first visit, always bump counters
                $db->prepare(
                    'UPDATE portal_tokens SET views = views + 1, view_count = view_count + 1, last_viewed = NOW(), first_viewed = COALESCE(first_viewed, NOW()) WHERE token = :t'
                )->execute([':t' => $rawToken]);
            } else {
                $error = 'This link is invalid or has expired. Please contact your service provider.';
            }
        } catch (Exception $e) {
            error_log('portal hex token lookup error: ' . $e->getMessage());
            $error = 'A server error occurred. Please try again later.';
        }

    } else {
        // ── Format B: base64(id:num) token — decode directly ─────
        $decoded = base64_decode(strtr($rawToken, '-_', '+/'), true);
        if ($decoded === false || strpos($decoded, ':') === false) {
            $error = 'Invalid link format. Please ask your service provider for a valid link.';
        } else {
            // "81:INV-2026-002" → invoice ID is the part before ':'
            $parts     = explode(':', $decoded, 2);
            $invoiceId = (int)$parts[0];
            if ($invoiceId <= 0) {
                $error = 'Invalid link. Invoice ID could not be determined.';
            }
            // Format B has no portal_tokens row — view tracking unavailable
            $firstViewed = null;
            $viewCount   = null;
        }
    }
}

if (!$error && $invoiceId > 0) {
    try {
        $db = getDB();

        // Fetch invoice — look up by id only (the number in the token is just for display)
        $stmt = $db->prepare("
            SELECT i.id AS invoice_id, i.invoice_number, i.issued_date AS issue_date,
                   i.due_date, i.grand_total AS amount, i.subtotal,
                   i.discount_pct, i.discount_amt, i.gst_amount,
                   i.status, i.client_id, i.service_type,
                   i.notes, i.terms, i.bank_details, i.currency
            FROM invoices i WHERE i.id = :id LIMIT 1
          ");
        $stmt->execute([':id' => $invoiceId]);
        $inv = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$inv) {
            $error = 'Invoice not found. The link may be outdated.';
        } else {
            // Client details
            $cStmt = $db->prepare(
                'SELECT name, email, phone, address FROM clients WHERE id = :id'
            );
            $cStmt->execute([':id' => $inv['client_id']]);
            $client = $cStmt->fetch(PDO::FETCH_ASSOC) ?: [];

            // Payment history
            $pStmt = $db->prepare(
                'SELECT amount, COALESCE(settlement_discount,0) AS settlement_discount,
                        payment_date, method, transaction_id, notes
                 FROM payments WHERE invoice_id = :id ORDER BY payment_date ASC'
            );
            $pStmt->execute([':id' => $inv['invoice_id']]);
            $payments = $pStmt->fetchAll(PDO::FETCH_ASSOC);

            // Company settings
            try {
                $sRows = $db->query("SELECT `key`, value FROM settings")->fetchAll(PDO::FETCH_ASSOC);
                foreach ($sRows as $r) $settings[$r['key']] = $r['value'];
            } catch (Exception $e) { /* settings table might differ */ }
        }
    } catch (Exception $e) {
        error_log('portal/index.php error: ' . $e->getMessage());
        $error = 'A server error occurred. Please try again later.';
    }
}

// ── Helpers ──────────────────────────────────────────────────
function fmt_date($d) {
    if (!$d || $d === '—') return '—';
    $ts = strtotime($d);
    return $ts ? date('d M Y', $ts) : htmlspecialchars($d);
}
function fmt_inr($n, $sym = '₹') {
    return $sym . number_format((float)$n, 2, '.', ',');
}
function status_col($s) {
    return match($s) {
        'Paid'      => '#388E3C',
        'Pending'   => '#F9A825',
        'Overdue'   => '#C62828',
        'Partial'   => '#E65100',
        'Draft'     => '#9E9E9E',
        'Cancelled' => '#757575',
        'Estimate'  => '#3949AB',
        default     => '#888'
    };
}
function status_bg($s) {
    return match($s) {
        'Paid'      => '#E8F5E9',
        'Pending'   => '#FFF8E1',
        'Overdue'   => '#FFEBEE',
        'Partial'   => '#FFF3E0',
        'Draft'     => '#F5F5F5',
        'Cancelled' => '#EEEEEE',
        'Estimate'  => '#E8EAF6',
        default     => '#F5F5F5'
    };
}
function status_label($s) {
    return match($s) {
        'Paid'      => '✓ Paid',
        'Pending'   => '⏳ Pending',
        'Overdue'   => '⚠ Overdue',
        'Partial'   => '◑ Partially Paid',
        'Draft'     => '✎ Draft',
        'Cancelled' => '✕ Cancelled',
        'Estimate'  => '📋 Estimate',
        default     => $s
    };
}

$sym           = $inv['currency'] ?: '₹';
$isEstimate    = ($inv['status'] ?? '') === 'Estimate';
$totalAmt      = (float)($inv['amount'] ?? 0);
$totalCash     = array_sum(array_column($payments, 'amount'));
$totalSettle   = array_sum(array_column($payments, 'settlement_discount'));
$totalPaid     = $totalCash;                          // cash received (shown as "Amount Paid")
$totalCovered  = $totalCash + $totalSettle;           // cash + settlement discount

// FIX: invoice marked Paid directly (no payment rows recorded) —
// treat full amount as paid so portal shows ₹0 balance, not full amount due
if (($inv['status'] ?? '') === 'Paid' && $totalCovered < 0.01) {
    $totalPaid    = $totalAmt;
    $totalCovered = $totalAmt;
}
// FIX: invoice marked Partial directly — show what's been covered
if (($inv['status'] ?? '') === 'Partial' && $totalCovered < 0.01) {
    $totalPaid    = 0;
    $totalCovered = 0;
}

$remaining     = max(0, $totalAmt - $totalCovered);
$pct           = $totalAmt > 0 ? min(100, round($totalCovered / $totalAmt * 100)) : 0;

$companyName    = $settings['company_name']    ?? 'OPTMS Tech';
$companyAddress = $settings['company_address'] ?? '';
$companyGST     = $settings['company_gst']     ?? '';
$companyEmail   = $settings['company_email']   ?? '';
$companyPhone   = $settings['company_phone']   ?? '';
$companyUPI     = $settings['company_upi']     ?? '';
$companyQR      = $settings['company_qr']      ?? '';

// ── Feature 4: Estimate expiry countdown ──────────────────────
$expiryDays  = null;
$expiryLabel = '';
if ($isEstimate && !empty($inv['due_date'])) {
    $now     = new DateTime('today');
    $due     = new DateTime($inv['due_date']);
    $diff    = (int)$now->diff($due)->days;
    $isPast  = $due < $now;
    $expiryDays  = $isPast ? -$diff : $diff;
    if ($isPast)   $expiryLabel = "⚠️ Expired " . $diff . " day" . ($diff != 1 ? "s" : "") . " ago";
    elseif ($diff == 0) $expiryLabel = "⏰ Expires today!";
    elseif ($diff <= 3) $expiryLabel = "⏳ Expires in " . $diff . " day" . ($diff != 1 ? "s" : "");
    else $expiryLabel = "✅ Valid for " . $diff . " more days";
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title><?= ($inv['status'] ?? '') === 'Estimate' ? 'Estimate' : 'Invoice' ?> <?= htmlspecialchars($inv['invoice_number'] ?? '') ?> — <?= htmlspecialchars($companyName) ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --teal:#00897B;--teal-bg:#E0F2F1;
  --green:#388E3C;--green-bg:#E8F5E9;
  --amber:#F9A825;--red:#C62828;--red-bg:#FFEBEE;--orange:#E65100;
  --muted:#6B7280;--border:#E5E7EB;--card:#fff;--bg:#F5F6FA;--text:#1A1A2E;
  --mono:'JetBrains Mono',monospace;--font:'Public Sans',-apple-system,sans-serif;
}
html{font-size:15px;background:var(--bg)}
body{font-family:var(--font);color:var(--text);min-height:100vh;padding:20px 16px 60px}
.wrap{max-width:700px;margin:0 auto}

.portal-header{background:linear-gradient(135deg,var(--teal),#00695C);border-radius:14px;padding:20px 24px;color:#fff;margin-bottom:20px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px}
.brand-logo{width:42px;height:42px;border-radius:10px;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center;font-size:18px;font-weight:800;color:#fff;flex-shrink:0}
.brand-name{font-size:16px;font-weight:800}
.brand-sub{font-size:11px;opacity:.75;margin-top:2px}
.inv-num{font-size:18px;font-weight:800;font-family:var(--mono)}
.status-pill{display:inline-flex;align-items:center;gap:5px;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;background:rgba(255,255,255,.2);border:1px solid rgba(255,255,255,.3);margin-top:4px}

.card{background:var(--card);border-radius:12px;border:1px solid var(--border);box-shadow:0 1px 4px rgba(0,0,0,.06);margin-bottom:16px}
.card-head{padding:13px 18px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:8px;font-size:13px;font-weight:700}
.card-head i{color:var(--teal);font-size:12px}
.card-body{padding:16px 18px}

.amount-strip{display:grid;grid-template-columns:1fr 1fr 1fr;gap:1px;background:var(--border);border-radius:0 0 12px 12px;overflow:hidden}
.amt-cell{background:var(--card);padding:14px;text-align:center}
.amt-cell .lbl{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:var(--muted);margin-bottom:4px}
.amt-cell .val{font-size:16px;font-weight:800;font-family:var(--mono)}

.progress-wrap{padding:10px 18px 14px;background:var(--bg);border-top:1px solid var(--border)}
.progress-bar{height:7px;background:#E5E7EB;border-radius:4px;overflow:hidden;margin-bottom:5px}
.progress-fill{height:100%;background:linear-gradient(90deg,#43A047,#66BB6A);border-radius:4px;transition:width .5s ease}
.progress-meta{display:flex;justify-content:space-between;font-size:11px;color:var(--muted)}

.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}
.info-item label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:var(--muted);display:block;margin-bottom:3px}
.info-item .val{font-size:13px;font-weight:600}

table{width:100%;border-collapse:collapse;font-size:13px}
th{padding:9px 12px;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);background:var(--bg);border-bottom:2px solid var(--border);text-align:left}
th.r,td.r{text-align:right}
td{padding:9px 12px;border-bottom:1px solid var(--border)}
tr:last-child td{border:none}

.pmt-row{display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--border)}
.tfoot-label{text-align:right;color:var(--muted);font-size:12px;padding:6px 12px}
.tfoot-val{font-family:var(--mono);font-size:13px;padding:6px 12px;text-align:right}
.tfoot-spacer{padding:0;border:none}
@media(max-width:600px){.tfoot-spacer{display:none}}
/* Line item cards for mobile */
.line-table{display:block}
.line-cards{display:none}
.line-card{padding:12px 16px;border-bottom:1px solid var(--border)}
.line-card:last-child{border:none}
.line-card-top{display:flex;justify-content:space-between;align-items:flex-start;gap:8px;margin-bottom:6px}
.line-card-name{font-weight:700;font-size:13px;flex:1}
.line-card-total{font-family:var(--mono);font-weight:800;font-size:14px;color:var(--teal);white-space:nowrap}
.line-card-meta{display:flex;gap:12px;font-size:11px;color:var(--muted)}
.line-card-meta span strong{color:var(--text);font-weight:600}
.line-tfoot{padding:10px 16px;background:var(--bg);border-top:2px solid var(--border)}
.line-tfoot-row{display:flex;justify-content:space-between;font-size:12px;color:var(--muted);padding:3px 0}
.line-tfoot-row.grand{font-size:15px;font-weight:800;color:var(--teal);padding-top:8px;margin-top:4px;border-top:1px dashed var(--border)}
.line-tfoot-row.grand span:first-child{color:var(--text)}
.tfoot-row td{padding:0;border:none}
.tfoot-inner{display:flex;justify-content:flex-end;align-items:center;gap:0;padding:5px 12px}
.tfoot-inner .lbl{color:var(--muted);font-size:12px;min-width:80px;text-align:right;padding-right:16px}
.tfoot-inner .val{font-family:var(--mono);font-size:13px;min-width:90px;text-align:right}
.tfoot-grand td{padding:0;border:none;border-top:2px solid var(--border);background:var(--bg)}
.tfoot-grand .tfoot-inner .lbl{font-weight:700;font-size:13px;color:var(--text)}
.tfoot-grand .tfoot-inner .val{font-size:16px;font-weight:800;color:var(--teal)}
.pmt-row:last-child{border:none}
.pmt-ic{width:32px;height:32px;border-radius:8px;background:var(--green-bg);color:var(--green);display:flex;align-items:center;justify-content:center;flex-shrink:0}
.pmt-info{flex:1;min-width:0}
.pmt-method{font-weight:600;font-size:12px}
.pmt-date{font-size:11px;color:var(--muted);margin-top:1px}
.pmt-txn{font-size:10px;color:var(--muted);font-family:var(--mono);margin-top:1px}
.pmt-amt{font-family:var(--mono);font-weight:700;color:var(--green);font-size:14px}

.upi-box{background:var(--teal-bg);border-radius:10px;padding:13px 16px;display:flex;align-items:center;gap:12px}
.upi-ic{width:36px;height:36px;border-radius:8px;background:var(--teal);color:#fff;display:flex;align-items:center;justify-content:center;font-size:15px;flex-shrink:0}
.upi-id{font-family:var(--mono);font-size:14px;font-weight:700;color:var(--teal)}
.copy-btn{margin-left:auto;padding:6px 14px;background:var(--teal);color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:12px;font-weight:600;font-family:var(--font);white-space:nowrap}
.copy-btn:hover{background:#00695C}

.footer{text-align:center;margin-top:24px;font-size:11px;color:var(--muted);line-height:1.9}
.error-box{background:#fff;border-radius:14px;border:2px solid #FFCDD2;padding:48px 32px;text-align:center;max-width:460px;margin:80px auto;box-shadow:0 4px 24px rgba(0,0,0,.08)}

@media print{
  body{padding:0;background:#fff}
  .sticky-bar,.upi-pay-btns,.wa-contact-btn,.pdf-btn,.copy-btn{display:none!important}
  .qr-section{display:block!important}
  .card{box-shadow:none;border:1px solid #ddd;break-inside:avoid}
  .portal-header{border-radius:0;print-color-adjust:exact;-webkit-print-color-adjust:exact}
}

/* UPI Pay buttons */
.upi-pay-btns{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}
.upi-pay-btn{flex:1;min-width:100px;display:flex;align-items:center;justify-content:center;gap:6px;padding:10px 12px;border-radius:10px;font-size:12px;font-weight:700;text-decoration:none;border:2px solid;transition:.2s;cursor:pointer}
.upi-pay-btn:active{transform:scale(.97)}
.btn-gpay{background:#fff;color:#1A1A2E;border-color:#E5E7EB}
.btn-phonepe{background:#5f259f;color:#fff;border-color:#5f259f}
.btn-paytm{background:#00BAF2;color:#fff;border-color:#00BAF2}
.btn-upi{background:var(--teal);color:#fff;border-color:var(--teal)}

/* Sticky header */
.sticky-bar{position:sticky;top:0;z-index:50;background:rgba(245,246,250,.95);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);padding:8px 0;margin-bottom:4px;display:none;align-items:center;justify-content:space-between;gap:8px;border-bottom:1px solid var(--border)}
.sticky-bar.show{display:flex}
.sticky-inv{font-family:var(--mono);font-weight:800;font-size:14px;color:var(--teal)}
.sticky-status{font-size:11px;font-weight:700;padding:3px 10px;border-radius:20px}

/* WhatsApp contact btn */
.wa-contact-btn{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:12px;background:#25D366;color:#fff;border-radius:10px;font-size:13px;font-weight:700;text-decoration:none;margin-top:10px;transition:.2s}
.wa-contact-btn:active{background:#1ebe57}

/* Download PDF btn */
.pdf-btn{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:11px;background:var(--bg);color:var(--text);border:2px solid var(--border);border-radius:10px;font-size:13px;font-weight:600;text-decoration:none;margin-top:8px;cursor:pointer;transition:.2s}
.pdf-btn:active{background:var(--border)}

/* Estimate banner */
.estimate-banner{background:linear-gradient(135deg,#E8EAF6,#C5CAE9);border:1.5px solid #9FA8DA;border-radius:12px;padding:16px 20px;margin-bottom:16px;display:flex;align-items:flex-start;gap:14px}
.estimate-banner-icon{width:42px;height:42px;background:#3949AB;border-radius:10px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:18px;flex-shrink:0}
.estimate-banner-body{flex:1}
.estimate-banner-title{font-size:15px;font-weight:800;color:#1A237E;margin-bottom:4px}
.estimate-banner-sub{font-size:12px;color:#3949AB;line-height:1.6}
.estimate-actions{display:flex;gap:10px;margin-top:14px;flex-wrap:wrap}
.btn-approve{flex:1;min-width:120px;display:flex;align-items:center;justify-content:center;gap:8px;padding:12px 16px;background:#388E3C;color:#fff;border:none;border-radius:10px;font-size:13px;font-weight:700;cursor:pointer;font-family:var(--font);transition:.2s;text-decoration:none}
.btn-approve:active{background:#2E7D32}
.btn-reject{flex:1;min-width:120px;display:flex;align-items:center;justify-content:center;gap:8px;padding:12px 16px;background:#fff;color:#C62828;border:2px solid #FFCDD2;border-radius:10px;font-size:13px;font-weight:700;cursor:pointer;font-family:var(--font);transition:.2s;text-decoration:none}
.btn-reject:active{background:#FFEBEE}
.estimate-responded{display:none;padding:12px 16px;border-radius:10px;font-size:13px;font-weight:700;text-align:center;margin-top:10px}

/* Progress label improvement */
.progress-meta .paid-label{font-weight:700;color:var(--green)}
.progress-meta .bal-label{font-weight:700;color:var(--red)}

/* Desktop: badge below invoice number, right aligned */
.inv-right{text-align:right}
.inv-num-row{display:flex;flex-direction:column;align-items:flex-end;gap:6px}

@media(max-width:600px){
  body{padding:12px 10px 80px}
  .portal-header{flex-direction:column;align-items:flex-start}
  /* Mobile: inv-right takes full width, badge inline at end */
  .inv-right{width:100%}
  .inv-num-row{flex-direction:row;align-items:center;justify-content:space-between;width:100%}
  .inv-num-row{display:flex;align-items:center;justify-content:space-between;width:100%;gap:8px}
  .info-grid{grid-template-columns:1fr 1fr}
  /* Hide table, show cards on mobile */
  .line-table{display:none}
  .line-cards{display:block}
  .amount-strip{grid-template-columns:1fr 1fr}
  /* Line items table — scrollable on mobile */
  .table-scroll{overflow-x:auto;-webkit-overflow-scrolling:touch;border-radius:0 0 var(--r) var(--r)}
  table{font-size:12px;min-width:420px}
  th,td{padding:8px 10px}
  .col-qty,.col-amount{display:none}
  .col-qty-h,.col-amount-h{display:none}
  .upi-pay-btns{gap:6px}
  .upi-pay-btn{font-size:11px;padding:9px 8px}
}
@media(max-width:400px){
  .amount-strip{grid-template-columns:1fr}
  table{min-width:360px;font-size:11px}
  th,td{padding:6px 6px}
}

/* Dynamic UPI QR */
.qr-section{text-align:center;margin-top:16px;padding-top:16px;border-top:1px dashed var(--border)}
.qr-label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:var(--muted);margin-bottom:10px}
.qr-wrap{display:inline-block;padding:10px;background:#fff;border-radius:12px;border:1px solid var(--border);box-shadow:0 2px 8px rgba(0,0,0,.07)}
.qr-wrap canvas,.qr-wrap img{display:block;border-radius:6px}
.qr-hint{font-size:11px;color:var(--muted);margin-top:8px}
.qr-amt{font-size:13px;font-weight:700;color:var(--teal);font-family:var(--mono);margin-top:4px}

/* ── #5 Overdue urgency banner ── */
.overdue-banner{display:flex;align-items:center;gap:12px;background:linear-gradient(135deg,#FFEBEE,#FFCDD2);border:1.5px solid #EF9A9A;border-radius:12px;padding:14px 18px;margin-bottom:16px}
.overdue-banner-icon{width:38px;height:38px;background:var(--red);border-radius:10px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:16px;flex-shrink:0}
.overdue-banner-body{flex:1}
.overdue-banner-title{font-size:14px;font-weight:800;color:#B71C1C}
.overdue-banner-sub{font-size:12px;color:#C62828;margin-top:2px}

/* ── #4 Invoice timeline ── */
.timeline-card{margin-bottom:16px}
.timeline{display:flex;align-items:flex-start;justify-content:space-between;position:relative;padding:8px 0 4px}
.timeline::before{content:'';position:absolute;top:22px;left:20px;right:20px;height:2px;background:var(--border);z-index:0}
.tl-step{display:flex;flex-direction:column;align-items:center;gap:6px;flex:1;position:relative;z-index:1}
.tl-dot{width:20px;height:20px;border-radius:50%;border:2px solid var(--border);background:var(--bg);display:flex;align-items:center;justify-content:center;font-size:9px}
.tl-dot.done{background:var(--green);border-color:var(--green);color:#fff}
.tl-dot.active{background:var(--teal);border-color:var(--teal);color:#fff;box-shadow:0 0 0 3px var(--teal-bg)}
.tl-dot.warn{background:var(--orange);border-color:var(--orange);color:#fff;box-shadow:0 0 0 3px #FFF3E0}
.tl-dot.overdue{background:var(--red);border-color:var(--red);color:#fff;box-shadow:0 0 0 3px var(--red-bg)}
.tl-label{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.4px;color:var(--muted);text-align:center;line-height:1.3}
.tl-date{font-size:9px;color:var(--muted);text-align:center;font-family:var(--mono)}

/* ── #2 Payment Receipt ── */
.receipt-card{border:2px dashed #A5D6A7!important;background:linear-gradient(135deg,#F9FFF9,#F1FFF3)!important}
.receipt-head{background:linear-gradient(135deg,#388E3C,#2E7D32);color:#fff;border-radius:10px 10px 0 0;padding:14px 20px;display:flex;align-items:center;justify-content:space-between}
.receipt-stamp{width:52px;height:52px;border:3px solid rgba(255,255,255,.5);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:800;text-transform:uppercase;color:#fff;text-align:center;line-height:1.2;flex-shrink:0}
.receipt-row{display:flex;justify-content:space-between;align-items:center;padding:8px 0;border-bottom:1px dashed #C8E6C9;font-size:12px}
.receipt-row:last-child{border:none}
.receipt-row .lbl{color:var(--muted);font-size:11px}
.receipt-row .val{font-weight:700;font-family:var(--mono)}

/* ── #9 Estimate → Invoice ref notice ── */
.estimate-ref-notice{display:flex;align-items:center;gap:10px;background:#EDE7F6;border:1px solid #CE93D8;border-radius:10px;padding:10px 14px;margin-bottom:16px;font-size:12px;color:#4A148C}
.estimate-ref-notice i{color:#7B1FA2;font-size:14px;flex-shrink:0}

/* ── #1 PDF download button ── */
.pdf-dl-btn{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:11px;background:var(--teal);color:#fff;border:none;border-radius:10px;font-size:13px;font-weight:700;cursor:pointer;font-family:var(--font);transition:.2s;margin-top:8px}
.pdf-dl-btn:hover{background:#00695C}
.pdf-dl-btn:active{transform:scale(.98)}
.pdf-dl-btn.loading{opacity:.7;pointer-events:none}

/* ── #8 Dark mode ── */
@media(prefers-color-scheme:dark){
  :root{
    --bg:#0F1117;--card:#1A1D27;--text:#E8EAF0;--border:#2A2D3A;
    --muted:#8B92A5;--teal:#26A69A;--teal-bg:#1A2E2C;
    --green:#4CAF50;--green-bg:#1A2E1B;--red-bg:#2E1A1A;
  }
  html{background:var(--bg)}
  .portal-header{background:linear-gradient(135deg,#00695C,#004D40)}
  .sticky-bar{background:rgba(15,17,23,.95)}
  .qr-wrap{background:#fff}
  .overdue-banner{background:linear-gradient(135deg,#2E1A1A,#3E1F1F);border-color:#6B2020}
  .overdue-banner-title{color:#EF9A9A}
  .overdue-banner-sub{color:#EF9A9A}
  .receipt-card{background:linear-gradient(135deg,#0F1F12,#122016)!important;border-color:#2E5430!important}
  .estimate-ref-notice{background:#1E1530;border-color:#4A2C6A;color:#CE93D8}
  .btn-gpay{background:#1A1D27;color:var(--text);border-color:var(--border)}
  .estimate-banner{background:linear-gradient(135deg,#1A1C30,#1E2040);border-color:#3949AB}
  .error-box{background:var(--card);border-color:#6B2020}
  table th{background:var(--bg)}
  .line-tfoot{background:var(--bg)}
  .progress-wrap{background:var(--bg)}
  .upi-box{background:var(--teal-bg)}
}

/* ── Feature 1: View tracking badge ── */
.view-badge{display:inline-flex;align-items:center;gap:5px;background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.25);border-radius:20px;padding:3px 10px;font-size:11px;font-weight:600;color:rgba(255,255,255,.9);margin-top:6px}
.view-badge i{font-size:10px}
.viewed-first{font-size:10px;color:var(--muted);text-align:center;margin-top:4px}

/* ── Feature 3: I've Paid button ── */
.ive-paid-btn{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:13px;background:linear-gradient(135deg,#1B5E20,#2E7D32);color:#fff;border:none;border-radius:10px;font-size:14px;font-weight:700;cursor:pointer;font-family:var(--font);transition:.2s;margin-top:12px;text-decoration:none}
.ive-paid-btn:active{transform:scale(.98);background:#1B5E20}

/* ── Feature 4: Expiry countdown ── */
.expiry-pill{display:inline-flex;align-items:center;gap:5px;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:700;margin-top:10px}
.expiry-pill.ok{background:#E8F5E9;color:#2E7D32}
.expiry-pill.warn{background:#FFF8E1;color:#E65100}
.expiry-pill.expired{background:#FFEBEE;color:#C62828}

/* ── Feature 5: Partial amount input ── */
.partial-pay-box{margin-top:14px;padding:14px;background:var(--bg);border-radius:10px;border:1px solid var(--border)}
.partial-pay-box label{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);display:block;margin-bottom:6px}
.partial-amt-row{display:flex;gap:8px;align-items:center}
.partial-amt-input{flex:1;padding:10px 12px;border:2px solid var(--border);border-radius:8px;font-size:15px;font-weight:700;font-family:var(--mono);color:var(--teal);background:var(--card);outline:none;transition:.2s}
.partial-amt-input:focus{border-color:var(--teal)}
.partial-upi-btn{padding:10px 16px;background:var(--teal);color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:700;cursor:pointer;font-family:var(--font);white-space:nowrap;transition:.2s}
.partial-upi-btn:active{background:#00695C}

/* ── Feature 7: Overdue WA dot ── */
.wa-dot{width:8px;height:8px;background:#C62828;border-radius:50%;display:inline-block;margin-left:4px;animation:pulse-dot 1.5s infinite}
@keyframes pulse-dot{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.6;transform:scale(1.3)}}

/* ── Feature 8: Language toggle ── */
.lang-toggle{position:fixed;bottom:20px;right:16px;z-index:100;display:flex;gap:6px}
.lang-btn{padding:7px 14px;border-radius:20px;font-size:12px;font-weight:700;border:2px solid var(--border);background:var(--card);color:var(--text);cursor:pointer;font-family:var(--font);transition:.2s;box-shadow:0 2px 8px rgba(0,0,0,.1)}
.lang-btn.active{background:var(--teal);color:#fff;border-color:var(--teal)}

/* ── Feature 9: Animated header ── */
@keyframes fadeSlideDown{from{opacity:0;transform:translateY(-16px)}to{opacity:1;transform:translateY(0)}}
@keyframes fadeIn{from{opacity:0}to{opacity:1}}
.portal-header{animation:fadeSlideDown .5s ease both}
.card{opacity:0}
.card.anim-done{opacity:1;transition:opacity .3s ease}

@media print{
  /* ── Reset & page setup ── */
  *{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important;color-adjust:exact!important}
  @page{margin:12mm 14mm;size:A4 portrait}
  body{padding:0!important;background:#fff!important;font-size:13px!important;color:#111!important}
  html{background:#fff!important;font-size:13px}

  /* ── Hide interactive / screen-only elements ── */
  .sticky-bar,.upi-pay-btns,.wa-contact-btn,.pdf-btn,.pdf-dl-btn,
  .copy-btn,.overdue-banner,.qr-hint,.estimate-actions,
  .btn-approve,.btn-reject{display:none!important}

  /* ── Show things normally hidden on screen ── */
  .qr-section,.receipt-card{display:block!important}

  /* ── Flatten card chrome — no shadows, subtle borders ── */
  .card{box-shadow:none!important;border:1px solid #ddd!important;border-radius:6px!important;margin-bottom:10px!important;break-inside:avoid}
  .card-head{padding:9px 14px!important;font-size:11px!important;background:#f8f8f8!important;border-bottom:1px solid #ddd!important}
  .card-body{padding:12px 14px!important}

  /* ── Header — keep gradient, reduce padding ── */
  .portal-header{border-radius:6px!important;padding:14px 18px!important;margin-bottom:10px!important;background:linear-gradient(135deg,#00897B,#00695C)!important;color:#fff!important}
  .brand-name{font-size:14px!important}
  .inv-num{font-size:16px!important}

  /* ── Amount strip ── */
  .amount-strip{border-radius:0 0 6px 6px!important}
  .amt-cell{padding:10px!important}
  .amt-cell .val{font-size:14px!important}

  /* ── Progress bar ── */
  .progress-wrap{padding:8px 14px 10px!important}
  .progress-bar{height:5px!important}

  /* ── Timeline compact ── */
  .timeline-card{break-inside:avoid}
  .tl-label{font-size:8px!important}
  .tl-date{font-size:8px!important}

  /* ── Tables ── */
  table{font-size:12px!important;min-width:unset!important}
  th{font-size:9px!important;padding:7px 10px!important}
  td{padding:7px 10px!important}
  .line-table{display:block!important}
  .line-cards{display:none!important}
  .col-qty,.col-amount,.col-qty-h,.col-amount-h{display:table-cell!important}

  /* ── Receipt card ── */
  .receipt-head{border-radius:4px 4px 0 0!important;padding:12px 16px!important}
  .receipt-stamp{width:44px!important;height:44px!important;font-size:8px!important}
  .receipt-row{padding:6px 0!important;font-size:11px!important}

  /* ── Info grid ── */
  .info-grid{gap:7px!important}
  .info-item .val{font-size:12px!important}
  .info-item label{font-size:9px!important}

  /* ── Payment rows ── */
  .pmt-row{padding:7px 0!important}
  .pmt-method{font-size:11px!important}
  .pmt-amt{font-size:12px!important}

  /* ── QR section — center and compact ── */
  .qr-section{margin-top:10px!important;padding-top:10px!important}
  .qr-wrap{padding:7px!important}

  /* ── Footer ── */
  .footer{margin-top:14px!important;font-size:10px!important;border-top:1px solid #ddd;padding-top:8px}

  /* ── Estimate banner ── */
  .estimate-banner{padding:10px 14px!important;margin-bottom:10px!important}
  .estimate-ref-notice{padding:7px 12px!important;margin-bottom:10px!important}

  /* ── Thank you card ── */
  .card[style*="linear-gradient(135deg, rgb(249"]{break-inside:avoid}

  /* ── Wrap max width ── */
  .wrap{max-width:100%!important}
}
</style>
</head>
<body>
<div class="wrap">

<!-- Sticky bar (shown on scroll) -->
<?php if (!$error && $inv): ?>
<div class="sticky-bar" id="stickyBar">
  <span class="sticky-inv"><?= htmlspecialchars($inv['invoice_number'] ?? '') ?></span>
  <span class="sticky-status" style="background:<?= status_bg($inv['status'] ?? '') ?>;color:<?= status_col($inv['status'] ?? '') ?>">
    <?= status_label($inv['status'] ?? '') ?>
  </span>
</div>
<?php endif; ?>
<?php if ($error): ?>
<div class="error-box">
  <i class="fas fa-link-slash" style="font-size:44px;color:#FFCDD2;display:block;margin-bottom:18px"></i>
  <h2 style="font-size:18px;margin-bottom:10px">Link Unavailable</h2>
  <p style="color:var(--muted);font-size:13px;line-height:1.7"><?= htmlspecialchars($error) ?></p>
  <div style="margin-top:24px;font-size:12px;color:var(--muted)">
    Powered by <strong><?= htmlspecialchars($companyName) ?></strong>
  </div>
</div>
<?php else: ?>

<!-- Header -->
<div class="portal-header">
  <div style="display:flex;align-items:center;gap:12px">
    <div class="brand-logo"><?= strtoupper(substr($companyName,0,2)) ?></div>
    <div>
      <div class="brand-name"><?= htmlspecialchars($companyName) ?></div>
      <?php if ($companyAddress): ?>
      <div class="brand-sub"><?= htmlspecialchars($companyAddress) ?></div>
      <?php endif; ?>
    </div>
  </div>
  <div class="inv-right">
    <div class="inv-num-row">
      <div class="inv-num"><?= htmlspecialchars($inv['invoice_number'] ?? '') ?></div>
      <div class="status-pill" style="background:<?= status_bg($inv['status'] ?? '') ?>;border-color:<?= status_col($inv['status'] ?? '') ?>40;color:<?= status_col($inv['status'] ?? '') ?>">
        <?= status_label($inv['status'] ?? '') ?>
      </div>
    </div>
    <?php if ($viewCount !== null): ?>
    <div class="view-badge">
      <i class="fas fa-eye"></i>
      <?= $viewCount ?> view<?= $viewCount != 1 ? 's' : '' ?>
      <?php if ($firstViewed): ?> · First seen <?= fmt_date($firstViewed) ?><?php endif; ?>
    </div>
    <?php endif; ?>
  </div>
</div>

<!-- Estimate notice banner -->
<?php if ($isEstimate): ?>
<?php
$isExpired = ($expiryDays !== null && $expiryDays < 0);
$waNumComp = preg_replace('/\D/', '', $companyPhone);
if (strlen($waNumComp) === 10) $waNumComp = '91' . $waNumComp;
$approveMsg = urlencode('Hi, I APPROVE the Estimate ' . ($inv['invoice_number'] ?? '') . ' for ' . $companyName . '. Please proceed.');
$feedbackMsg = urlencode('Hi, I have feedback on Estimate ' . ($inv['invoice_number'] ?? '') . ' from ' . $companyName . '. ');
$contactMsg  = urlencode('Hi ' . $companyName . ', I viewed Estimate ' . ($inv['invoice_number'] ?? '') . ' which has expired. Can you send a revised quote?');
?>

<?php if ($isExpired): ?>
<!-- EXPIRED: Red locked banner (Option A) -->
<div class="estimate-banner" style="background:linear-gradient(135deg,#FFEBEE,#FFCDD2);border-color:#EF9A9A">
  <div class="estimate-banner-icon" style="background:#C62828"><i class="fas fa-clock"></i></div>
  <div class="estimate-banner-body">
    <div class="estimate-banner-title" style="color:#B71C1C">⏰ This Estimate Has Expired</div>
    <div class="estimate-banner-sub" style="color:#C62828">
      This estimate expired on <strong><?= fmt_date($inv['due_date'] ?? '') ?></strong>
      (<?= abs($expiryDays) ?> day<?= abs($expiryDays) != 1 ? 's' : '' ?> ago).<br>
      Please contact <strong><?= htmlspecialchars($companyName) ?></strong> to request a revised quote.
    </div>
    <div class="expiry-pill expired" style="margin-top:10px">
      ⚠️ Expired <?= abs($expiryDays) ?> day<?= abs($expiryDays) != 1 ? 's' : '' ?> ago
    </div>
    <!-- Buttons disabled/locked -->
    <div class="estimate-actions" style="margin-top:14px">
      <div class="btn-approve" style="opacity:.4;cursor:not-allowed;pointer-events:none;background:#9E9E9E;border-color:#9E9E9E">
        <i class="fas fa-lock"></i> Approval Locked
      </div>
      <a href="https://wa.me/<?= $waNumComp ?>?text=<?= $contactMsg ?>" class="btn-reject" style="background:#fff;color:#C62828;border-color:#FFCDD2" target="_blank">
        <i class="fab fa-whatsapp"></i> Request New Quote
      </a>
    </div>
  </div>
</div>

<?php else: ?>
<!-- ACTIVE: Normal estimate banner -->
<div class="estimate-banner">
  <div class="estimate-banner-icon"><i class="fas fa-file-alt"></i></div>
  <div class="estimate-banner-body">
    <div class="estimate-banner-title">📋 This is an Estimate / Quotation</div>
    <div class="estimate-banner-sub">
      This is <strong>not a final invoice</strong>. Actual charges may vary based on the final scope of work.<br>
      Valid until: <strong><?= fmt_date($inv['due_date'] ?? '') ?></strong>
    </div>
    <?php if ($expiryLabel): ?>
    <div class="expiry-pill <?= $expiryDays === null ? '' : ($expiryDays <= 3 ? 'warn' : 'ok') ?>">
      <?= htmlspecialchars($expiryLabel) ?>
    </div>
    <?php endif; ?>
    <div class="estimate-actions">
      <a href="https://wa.me/<?= $waNumComp ?>?text=<?= $approveMsg ?>" class="btn-approve" target="_blank">
        <i class="fas fa-check-circle"></i> Approve via WhatsApp
      </a>
      <a href="https://wa.me/<?= $waNumComp ?>?text=<?= $feedbackMsg ?>" class="btn-reject" target="_blank">
        <i class="fas fa-comment-dots"></i> Request Changes
      </a>
    </div>
  </div>
</div>
<?php endif; ?>
<?php endif; ?>

<?php if ($isExpired && $waNumComp): ?>
<script>
// Option D: notify company when expired estimate viewed (once per session)
(function() {
  var flagKey = 'notified_<?= preg_replace("/[^a-z0-9]/i", "", $inv["invoice_number"] ?? "x") ?>';
  if (sessionStorage.getItem(flagKey)) return;
  sessionStorage.setItem(flagKey, '1');
  setTimeout(function() {
    var msg = encodeURIComponent(
      '🔔 *Expired Estimate Viewed*\n\n' +
      'Client opened expired Estimate *<?= addslashes($inv["invoice_number"] ?? "") ?>*\n' +
      'Client: *<?= addslashes($client["name"] ?? "Unknown") ?>*\n' +
      'Expired <?= abs((int)$expiryDays) ?> day<?= abs((int)$expiryDays) != 1 ? "s" : "" ?> ago (<?= fmt_date($inv["due_date"] ?? "") ?>)\n\n' +
      'Send a revised quote!'
    );
    window.open('https://wa.me/<?= $waNumComp ?>?text=' + msg, '_blank');
  }, 2500);
})();
</script>
<?php endif; ?>

<?php
// ── #5 Overdue urgency banner ──────────────────────────────
$daysOverdue = 0;
if (($inv['status'] ?? '') === 'Overdue' && !empty($inv['due_date'])) {
    $daysOverdue = (int)floor((time() - strtotime($inv['due_date'])) / 86400);
}
?>
<?php if (($inv['status'] ?? '') === 'Overdue'): ?>
<div class="overdue-banner">
  <div class="overdue-banner-icon"><i class="fas fa-exclamation-triangle"></i></div>
  <div class="overdue-banner-body">
    <div class="overdue-banner-title">Payment Overdue<?= $daysOverdue > 0 ? ' by ' . $daysOverdue . ' day' . ($daysOverdue > 1 ? 's' : '') : '' ?></div>
    <div class="overdue-banner-sub">This invoice was due on <strong><?= fmt_date($inv['due_date'] ?? '') ?></strong>. Please clear the balance at the earliest.</div>
  </div>
</div>
<?php endif; ?>

<?php
// ── #4 Invoice timeline ────────────────────────────────────
// Steps: Issued → Viewed → Partial → Paid/Overdue
$tlStatus  = $inv['status'] ?? '';
$tlIssued  = !empty($inv['issue_date']);
$tlViewed  = true; // they're viewing it right now
$tlPartial = in_array($tlStatus, ['Partial','Paid']);
$tlPaid    = ($tlStatus === 'Paid');
$tlOverdue = ($tlStatus === 'Overdue');
?>
<?php if (!$isEstimate): ?>
<div class="card timeline-card">
  <div class="card-head"><i class="fas fa-stream"></i> <span data-t="Invoice Timeline">Invoice Timeline</span></div>
  <div class="card-body" style="padding:14px 18px 18px">
    <div class="timeline">
      <div class="tl-step">
        <div class="tl-dot done"><i class="fas fa-check" style="font-size:8px"></i></div>
        <div class="tl-label" data-t="Issued">Issued</div>
        <div class="tl-date"><?= fmt_date($inv['issue_date'] ?? '') ?></div>
      </div>
      <div class="tl-step">
        <div class="tl-dot done"><i class="fas fa-eye" style="font-size:8px"></i></div>
        <div class="tl-label" data-t="Viewed">Viewed</div>
        <div class="tl-date"><?= $firstViewed ? fmt_date($firstViewed) : 'Now' ?></div>
      </div>
      <?php if ($tlStatus === 'Paid'): ?>
      <?php
        // FIX: if paid directly (no payment rows), fall back to issue_date
        $paidDateStr = !empty($payments)
            ? fmt_date(end($payments)['payment_date'])
            : (!empty($inv['issue_date']) ? fmt_date($inv['issue_date']) : '—');
      ?>
      <div class="tl-step">
        <div class="tl-dot done"><i class="fas fa-check" style="font-size:8px"></i></div>
        <div class="tl-label" data-t="Paid">Paid</div>
        <div class="tl-date"><?= $paidDateStr ?></div>
      </div>
      <?php elseif ($tlStatus === 'Partial'): ?>
      <div class="tl-step">
        <div class="tl-dot warn"><i class="fas fa-adjust" style="font-size:8px"></i></div>
        <div class="tl-label" data-t="Partial">Partial</div>
        <div class="tl-date"><?= !empty($payments) ? fmt_date(end($payments)['payment_date']) : '—' ?></div>
      </div>
      <div class="tl-step">
        <div class="tl-dot active"><i class="fas fa-clock" style="font-size:8px"></i></div>
        <div class="tl-label" data-t="Balance">Balance</div>
        <div class="tl-date">Due <?= fmt_date($inv['due_date'] ?? '') ?></div>
      </div>
      <?php elseif ($tlOverdue): ?>
      <div class="tl-step">
        <div class="tl-dot overdue"><i class="fas fa-times" style="font-size:8px"></i></div>
        <div class="tl-label" data-t="Overdue">Overdue</div>
        <div class="tl-date">Since <?= fmt_date($inv['due_date'] ?? '') ?></div>
      </div>
      <?php else: ?>
      <div class="tl-step">
        <div class="tl-dot active"><i class="fas fa-clock" style="font-size:8px"></i></div>
        <div class="tl-label" data-t="Pending">Pending</div>
        <div class="tl-date">Due <?= fmt_date($inv['due_date'] ?? '') ?></div>
      </div>
      <?php endif; ?>
    </div>
  </div>
</div>
<?php endif; ?>

<!-- Amount summary -->
<div class="card">
  <div class="amount-strip" style="border-radius:12px 12px 0 0">
    <div class="amt-cell">
      <div class="lbl" data-t="Invoice Total"><?= $isEstimate ? 'Estimated Total' : 'Invoice Total' ?></div>
      <div class="val" style="color:var(--teal)"><?= fmt_inr($totalAmt, $sym) ?></div>
    </div>
    <?php if ($isEstimate): ?>
    <div class="amt-cell">
      <div class="lbl">Valid Until</div>
      <div class="val" style="color:#3949AB;font-size:13px"><?= fmt_date($inv['due_date'] ?? '') ?></div>
    </div>
    <div class="amt-cell">
      <div class="lbl">Status</div>
      <div class="val" style="color:#3949AB;font-size:13px">Awaiting Approval</div>
    </div>
    <?php else: ?>
    <div class="amt-cell">
      <div class="lbl" data-t="Amount Paid">Amount Paid</div>
      <div class="val" style="color:var(--green)"><?= fmt_inr($totalCovered, $sym) ?></div>
      <?php if ($totalSettle > 0.01): ?>
      <div style="font-size:10px;color:#E65100;margin-top:2px">
        <?= fmt_inr($totalCash, $sym) ?> cash + <?= fmt_inr($totalSettle, $sym) ?> discount
      </div>
      <?php endif; ?>
    </div>
    <div class="amt-cell">
      <div class="lbl" data-t="Balance Due"><?= $remaining > 0 ? 'Balance Due' : 'Status' ?></div>
      <div class="val" style="color:<?= $remaining > 0 ? 'var(--red)' : 'var(--green)' ?>">
        <?= $remaining > 0 ? fmt_inr($remaining, $sym) : '✓ Cleared' ?>
      </div>
    </div>
    <?php endif; ?>
  </div>
  <?php if ($totalAmt > 0 && !$isEstimate): ?>
  <div class="progress-wrap">
    <div class="progress-bar"><div class="progress-fill" style="width:<?= $pct ?>%"></div></div>
    <div class="progress-meta">
      <span class="paid-label"><?= fmt_inr($totalCovered, $sym) ?> paid of <?= fmt_inr($totalAmt, $sym) ?> (<?= $pct ?>%)</span>
      <?php if ($remaining > 0.01): ?>
      <span class="bal-label"><?= fmt_inr($remaining, $sym) ?> remaining</span>
      <?php else: ?>
      <span style="color:var(--green);font-weight:700">✓ Fully Paid</span>
      <?php endif; ?>
    </div>
  </div>
  <?php endif; ?>
</div>

<!-- #9 Estimate → Invoice conversion notice -->
<?php
$estRef = $settings['estimate_ref_' . ($inv['invoice_id'] ?? '')] ?? '';
// Also check if invoice_number suggests a converted estimate (e.g. service_type has "EST-" ref stored in notes)
$estRefInNotes = '';
if (!$isEstimate && !empty($inv['notes'])) {
    if (preg_match('/(?:estimate|quote|quotation)[:\s#]+([A-Z0-9\-]+)/i', $inv['notes'], $m)) {
        $estRefInNotes = $m[1];
    }
}
?>
<?php if (!$isEstimate && $estRefInNotes): ?>
<div class="estimate-ref-notice">
  <i class="fas fa-link"></i>
  <span>Originally quoted as Estimate <strong><?= htmlspecialchars($estRefInNotes) ?></strong> — converted to this invoice.</span>
</div>
<?php endif; ?>

<!-- Invoice / Estimate details -->
<div class="card">
  <div class="card-head"><i class="fas fa-file-invoice"></i> <?= $isEstimate ? 'Estimate Details' : 'Invoice Details' ?></div>
  <div class="card-body">
    <div class="info-grid">
      <div class="info-item"><label><?= $isEstimate ? 'Quote #' : 'Invoice #' ?></label><span class="val" style="font-family:var(--mono)"><?= htmlspecialchars($inv['invoice_number'] ?? '') ?></span></div>
      <div class="info-item"><label data-t="Service">Service</label><span class="val"><?= htmlspecialchars($inv['service_type'] ?? '—') ?></span></div>
      <div class="info-item"><label><?= $isEstimate ? 'Date Issued' : 'Issue Date' ?></label><span class="val"><?= fmt_date($inv['issue_date'] ?? '') ?></span></div>
      <div class="info-item"><label><?= $isEstimate ? 'Valid Until' : 'Due Date' ?></label>
        <span class="val" style="color:<?= (!$isEstimate && $inv['status']==='Overdue') ? 'var(--red)' : 'inherit' ?>">
          <?= fmt_date($inv['due_date'] ?? '') ?>
          <?php if (!$isEstimate && $inv['status']==='Overdue'): ?> <i class="fas fa-exclamation-triangle" style="color:var(--red);font-size:11px"></i><?php endif; ?>
        </span>
      </div>
      <?php if (!empty($inv['gst_rate'])): ?>
      <div class="info-item"><label data-t="GST Rate">GST Rate</label><span class="val"><?= htmlspecialchars($inv['gst_rate']) ?>%</span></div>
      <?php endif; ?>
      <?php if (!empty($inv['discount']) && $inv['discount'] != '0' && $inv['discount'] != '0.00'): ?>
      <div class="info-item"><label data-t="Discount">Discount</label><span class="val"><?= htmlspecialchars($inv['discount']) ?></span></div>
      <?php endif; ?>
    </div>
  </div>
</div>

<!-- Client info -->
<?php if ($client && !empty($client['name'])): ?>
<div class="card">
  <div class="card-head"><i class="fas fa-user"></i> <span data-t="Billed To">Billed To</span></div>
  <div class="card-body">
    <div class="info-grid">
      <div class="info-item"><label data-t="Name">Name</label><span class="val"><?= htmlspecialchars($client['name']) ?></span></div>
      <?php if (!empty($client['email'])): ?><div class="info-item"><label data-t="Email">Email</label><span class="val"><?= htmlspecialchars($client['email']) ?></span></div><?php endif; ?>
      <?php if (!empty($client['phone'])): ?><div class="info-item"><label data-t="Phone">Phone</label><span class="val"><?= htmlspecialchars($client['phone']) ?></span></div><?php endif; ?>
      <?php if (!empty($client['address'])): ?><div class="info-item" style="grid-column:1/-1"><label data-t="Address">Address</label><span class="val" style="font-weight:400"><?= nl2br(htmlspecialchars($client['address'])) ?></span></div><?php endif; ?>
    </div>
  </div>
</div>
<?php endif; ?>

<!-- Line items -->
<?php
$iStmt = $db->prepare('SELECT description AS name, quantity AS qty, rate, gst_rate AS gst, line_total AS total FROM invoice_items WHERE invoice_id = :id ORDER BY sort_order ASC');
$iStmt->execute([':id' => $inv['invoice_id']]);
$items = $iStmt->fetchAll(PDO::FETCH_ASSOC);
if ($items):
?>
<div class="card" style="padding:0">
  <div class="card-head" style="padding:14px 18px"><i class="fas fa-list-ul"></i> <?= $isEstimate ? 'Estimate Items' : 'Line Items' ?></div>

  <!-- Desktop table -->
  <div class="line-table">
  <div class="table-scroll">
  <table>
    <thead><tr>
      <th style="width:28px">#</th>
      <th>Description</th>
      <th class="r col-qty-h">Qty</th>
      <th class="r">Rate</th>
      <th class="r col-amount-h">Amount</th>
      <th class="r">GST</th>
      <th class="r">Total</th>
    </tr></thead>
    <tbody>
    <?php foreach ($items as $i => $item): ?>
    <tr>
      <td style="color:var(--muted);font-size:11px"><?= $i+1 ?></td>
      <td>
        <strong style="font-size:13px"><?= htmlspecialchars($item['name'] ?? $item['desc'] ?? '') ?></strong>
        <?php if (!empty($item['type'])): ?><br><span style="font-size:10px;color:var(--muted)"><?= htmlspecialchars($item['type']) ?></span><?php endif; ?>
      </td>
      <?php
        $lineQty    = (float)($item['qty']  ?? 1);
        $lineRate   = (float)($item['rate'] ?? 0);
        $lineGstPct = (float)($item['gst']  ?? 0);
        $lineAmt    = $lineQty * $lineRate;
        $lineGstAmt = $lineAmt * $lineGstPct / 100;
        $lineTotal  = $lineAmt + $lineGstAmt;
      ?>
      <td class="r col-qty"><?= number_format($lineQty, 2) ?></td>
      <td class="r" style="font-family:var(--mono)"><?= fmt_inr($lineRate, '') ?></td>
      <td class="r col-amount" style="font-family:var(--mono)"><?= fmt_inr($lineAmt, '') ?></td>
      <td class="r" style="white-space:nowrap"><?= number_format($lineGstPct, 2) ?>%</td>
      <td class="r" style="font-family:var(--mono);font-weight:700;white-space:nowrap"><?= fmt_inr($lineTotal, $sym) ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    <?php
      // Compute totals from items
      $calcSubtotal  = 0; $calcGst = 0;
      foreach ($items as $item) {
        $q = (float)($item['qty'] ?? 1);
        $r = (float)($item['rate'] ?? 0);
        $g = (float)($item['gst'] ?? 0);
        $a = $q * $r;
        $calcSubtotal += $a;
        $calcGst      += $a * $g / 100;
      }
      $discountAmt = (float)($inv['discount_amt'] ?? 0);
      $discountPct = (float)($inv['discount_pct'] ?? 0);
      if ($discountAmt == 0 && $discountPct > 0) {
        $discountAmt = $calcSubtotal * $discountPct / 100;
      }
      $calcGrandTotal = $calcSubtotal - $discountAmt + $calcGst;
    ?>
    <tfoot>
      <tr class="tfoot-row"><td colspan="7"><div class="tfoot-inner"><span class="lbl">Subtotal</span><span class="val"><?= fmt_inr($calcSubtotal, $sym) ?></span></div></td></tr>
      <?php if ($discountAmt > 0):
        $amtAfterDisc = $calcSubtotal - $discountAmt;
        $discFactor   = $calcSubtotal > 0 ? (1 - $discountAmt / $calcSubtotal) : 1;
        $calcGstAfter = $calcGst * $discFactor;
        $calcGrandTotal = $amtAfterDisc + $calcGstAfter;
      ?>
      <tr class="tfoot-row"><td colspan="7"><div class="tfoot-inner"><span class="lbl">Discount<?= $discountPct > 0 ? ' ('.(int)$discountPct.'%)' : '' ?></span><span class="val" style="color:var(--red)">− <?= fmt_inr($discountAmt, $sym) ?></span></div></td></tr>
      <tr class="tfoot-row"><td colspan="7"><div class="tfoot-inner"><span class="lbl">After Discount</span><span class="val" style="font-weight:600"><?= fmt_inr($amtAfterDisc, $sym) ?></span></div></td></tr>
      <tr class="tfoot-row"><td colspan="7"><div class="tfoot-inner"><span class="lbl">GST</span><span class="val"><?= fmt_inr($calcGstAfter, $sym) ?></span></div></td></tr>
      <?php else: ?>
      <tr class="tfoot-row"><td colspan="7"><div class="tfoot-inner"><span class="lbl">GST</span><span class="val"><?= fmt_inr($calcGst, $sym) ?></span></div></td></tr>
      <?php endif; ?>
      <tr class="tfoot-grand"><td colspan="7"><div class="tfoot-inner"><span class="lbl">Grand Total</span><span class="val"><?= fmt_inr($calcGrandTotal, $sym) ?></span></div></td></tr>
    </tfoot>
  </table>
  </div><!-- end table-scroll -->
  </div><!-- end line-table -->

  <!-- Mobile card view -->
  <?php
    // Re-compute totals for cards (already done above in tfoot php block)
    $mc_subtotal = 0; $mc_gst = 0;
    foreach ($items as $item) {
      $q = (float)($item['qty'] ?? 1); $r = (float)($item['rate'] ?? 0); $g = (float)($item['gst'] ?? 0);
      $mc_subtotal += $q * $r; $mc_gst += $q * $r * $g / 100;
    }
    $mc_discount = (float)($inv['discount_amt'] ?? 0);
    if ($mc_discount == 0 && (float)($inv['discount_pct'] ?? 0) > 0)
      $mc_discount = $mc_subtotal * (float)$inv['discount_pct'] / 100;
    $mc_grand = $mc_subtotal - $mc_discount + $mc_gst;
  ?>
  <div class="line-cards">
    <?php foreach ($items as $ci => $item):
      $q = (float)($item['qty'] ?? 1); $r = (float)($item['rate'] ?? 0);
      $g = (float)($item['gst'] ?? 0); $amt = $q * $r; $tot = $amt + $amt * $g / 100;
    ?>
    <div class="line-card">
      <div class="line-card-top">
        <div class="line-card-name"><?= htmlspecialchars($item['name'] ?? '') ?></div>
        <div class="line-card-total"><?= fmt_inr($tot, $sym) ?></div>
      </div>
      <div class="line-card-meta">
        <span>Qty: <strong><?= number_format($q, 2) ?></strong></span>
        <span>Rate: <strong><?= fmt_inr($r, $sym) ?></strong></span>
        <?php if ($g > 0): ?><span>GST: <strong><?= number_format($g,2) ?>%</strong></span><?php endif; ?>
      </div>
    </div>
    <?php endforeach; ?>
    <div class="line-tfoot">
      <div class="line-tfoot-row"><span>Subtotal</span><span style="font-family:var(--mono)"><?= fmt_inr($mc_subtotal, $sym) ?></span></div>
      <?php if ($mc_discount > 0):
        $mc_after_disc  = $mc_subtotal - $mc_discount;
        $mc_disc_factor = $mc_subtotal > 0 ? (1 - $mc_discount / $mc_subtotal) : 1;
        $mc_gst_after   = $mc_gst * $mc_disc_factor;
        $mc_grand       = $mc_after_disc + $mc_gst_after;
        $mc_disc_pct    = (float)($inv['discount_pct'] ?? 0);
      ?>
      <div class="line-tfoot-row" style="color:var(--red)">
        <span>Discount<?= $mc_disc_pct > 0 ? ' (' . (int)$mc_disc_pct . '%)' : '' ?></span>
        <span style="font-family:var(--mono)">− <?= fmt_inr($mc_discount, $sym) ?></span>
      </div>
      <div class="line-tfoot-row"><span>After Discount</span><span style="font-family:var(--mono);font-weight:600"><?= fmt_inr($mc_after_disc, $sym) ?></span></div>
      <div class="line-tfoot-row"><span>GST</span><span style="font-family:var(--mono)"><?= fmt_inr($mc_gst_after, $sym) ?></span></div>
      <?php else: ?>
      <div class="line-tfoot-row"><span>GST</span><span style="font-family:var(--mono)"><?= fmt_inr($mc_gst, $sym) ?></span></div>
      <?php endif; ?>
      <div class="line-tfoot-row grand"><span>Grand Total</span><span style="font-family:var(--mono)"><?= fmt_inr($mc_grand, $sym) ?></span></div>
    </div>
  </div><!-- end line-cards -->

</div>
<?php endif; ?>

<!-- Payment history (not shown for estimates) -->
<?php if ($payments && !$isEstimate): ?>
<div class="card">
  <div class="card-head"><i class="fas fa-receipt"></i> <span data-t="Payment History">Payment History</span></div>
  <div class="card-body" style="padding:0 18px">
    <?php foreach ($payments as $p): ?>
    <div class="pmt-row">
      <div class="pmt-ic"><i class="fas fa-check"></i></div>
      <div class="pmt-info">
        <div class="pmt-method"><?= htmlspecialchars($p['method'] ?? 'Payment') ?></div>
        <div class="pmt-date"><?= fmt_date($p['payment_date'] ?? '') ?></div>
        <?php if (!empty($p['transaction_id'])): ?>
        <div class="pmt-txn">Ref: <?= htmlspecialchars($p['transaction_id']) ?></div>
        <?php endif; ?>
        <?php if (!empty($p['notes'])): ?>
        <div class="pmt-txn"><?= htmlspecialchars($p['notes']) ?></div>
        <?php endif; ?>
      </div>
      <div style="text-align:right">
        <div class="pmt-amt"><?= fmt_inr($p['amount'], $sym) ?></div>
        <?php if (!empty($p['settlement_discount']) && (float)$p['settlement_discount'] > 0.01): ?>
        <div style="font-size:10px;color:#E65100;margin-top:2px">+<?= fmt_inr($p['settlement_discount'], $sym) ?> disc</div>
        <?php endif; ?>
      </div>
    </div>
    <?php endforeach; ?>
    <?php if ($totalSettle > 0.01): ?>
    <div style="display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-top:1px dashed var(--border);margin-top:4px;font-size:12px">
      <span style="color:#E65100;font-weight:700">✂ Total Settlement Discount</span>
      <span style="color:#E65100;font-weight:700;font-family:var(--mono)">-<?= fmt_inr($totalSettle, $sym) ?></span>
    </div>
    <?php endif; ?>
  </div>
</div>
<?php endif; ?>

<!-- #2 Payment Receipt (shown when fully Paid) -->
<?php if (($inv['status'] ?? '') === 'Paid' && $payments): ?>
<?php
  $lastPmt    = end($payments);
  $receiptNum = 'RCPT-' . strtoupper(substr(md5($inv['invoice_number'].$totalCash), 0, 8));
?>
<div class="card receipt-card">
  <div class="receipt-head">
    <div>
      <div style="font-size:11px;opacity:.75;margin-bottom:2px;text-transform:uppercase;letter-spacing:.5px">Payment Receipt</div>
      <div style="font-size:17px;font-weight:800;font-family:var(--mono)"><?= $receiptNum ?></div>
    </div>
    <div class="receipt-stamp">PAID<br>✓</div>
  </div>
  <div class="card-body">
    <div class="receipt-row">
      <span class="lbl">Invoice</span>
      <span class="val"><?= htmlspecialchars($inv['invoice_number'] ?? '') ?></span>
    </div>
    <div class="receipt-row">
      <span class="lbl">Client</span>
      <span class="val"><?= htmlspecialchars($client['name'] ?? '—') ?></span>
    </div>
    <div class="receipt-row">
      <span class="lbl">Amount Paid</span>
      <span class="val" style="color:var(--green);font-size:15px"><?= fmt_inr($totalCash, $sym) ?></span>
    </div>
    <?php if ($totalSettle > 0.01): ?>
    <div class="receipt-row">
      <span class="lbl">Settlement Discount</span>
      <span class="val" style="color:var(--orange)">− <?= fmt_inr($totalSettle, $sym) ?></span>
    </div>
    <?php endif; ?>
    <div class="receipt-row">
      <span class="lbl">Payment Method</span>
      <span class="val"><?= htmlspecialchars($lastPmt['method'] ?? 'UPI') ?></span>
    </div>
    <?php if (!empty($lastPmt['transaction_id'])): ?>
    <div class="receipt-row">
      <span class="lbl">Transaction Ref</span>
      <span class="val"><?= htmlspecialchars($lastPmt['transaction_id']) ?></span>
    </div>
    <?php endif; ?>
    <div class="receipt-row">
      <span class="lbl">Payment Date</span>
      <span class="val"><?= fmt_date($lastPmt['payment_date'] ?? '') ?></span>
    </div>
    <div class="receipt-row">
      <span class="lbl">Issued By</span>
      <span class="val"><?= htmlspecialchars($companyName) ?></span>
    </div>
    <div style="text-align:center;margin-top:14px;padding-top:12px;border-top:1px dashed #C8E6C9">
      <div style="font-size:11px;color:var(--muted)">This is an auto-generated payment receipt</div>
      <button class="pdf-dl-btn" style="max-width:260px;margin:10px auto 0" onclick="downloadPDF()">
        <i class="fas fa-file-download"></i> Download Receipt as PDF
      </button>
    </div>
  </div>
</div>
<?php endif; ?>
<?php if ($remaining > 0.01 && $companyUPI && !$isEstimate): ?>
<div class="card">
  <div class="card-head"><i class="fas fa-mobile-alt"></i> <span data-t="Pay Now">Pay Now</span></div>
  <div class="card-body">
    <p style="font-size:12px;color:var(--muted);margin-bottom:12px">
      Pay the remaining <strong style="color:var(--red)"><?= fmt_inr($remaining, $sym) ?></strong> via UPI:
    </p>
    <div class="upi-box">
      <div class="upi-ic"><i class="fas fa-rupee-sign"></i></div>
      <div>
        <div style="font-size:9px;font-weight:700;text-transform:uppercase;color:var(--muted);margin-bottom:2px">UPI ID</div>
        <div class="upi-id" id="upiId"><?= htmlspecialchars($companyUPI) ?></div>
      </div>
      <button class="copy-btn" onclick="copyUPI()" id="copyBtn"><i class="fas fa-copy"></i> Copy</button>
    </div>

    <!-- UPI App deep links -->
    <?php
      $upiEncoded = urlencode($companyUPI);
      $payeeName  = urlencode($companyName);
      $amtParam   = number_format($remaining, 2, '.', '');
      $upiBase    = "upi://pay?pa={$upiEncoded}&pn={$payeeName}&am={$amtParam}&cu=INR";
    ?>
    <div class="upi-pay-btns">
      <a href="<?= $upiBase ?>&mode=00&purpose=00" class="upi-pay-btn btn-gpay">
        <i class="fas fa-wallet"></i> GPay
      </a>
      <a href="phonepe://pay?pa=<?= $upiEncoded ?>&pn=<?= $payeeName ?>&am=<?= $amtParam ?>&cu=INR" class="upi-pay-btn btn-phonepe">
        <i class="fas fa-bolt"></i> PhonePe
      </a>
      <a href="paytmmp://pay?pa=<?= $upiEncoded ?>&pn=<?= $payeeName ?>&am=<?= $amtParam ?>&cu=INR" class="upi-pay-btn btn-paytm">
        <i class="fas fa-mobile-alt"></i> Paytm
      </a>
    </div>
    <!-- Dynamic UPI QR Code — only for Pending, Overdue, Partial -->
    <?php $invStatus = $inv['status'] ?? ''; ?>
    <?php if (in_array($invStatus, ['Pending', 'Overdue', 'Partial'])): ?>
    <div class="qr-section">
      <div class="qr-label" data-t="Scan to Pay"><i class="fas fa-qrcode"></i> <span data-t="Scan to Pay">Scan to Pay</span></div>
      <div class="qr-wrap">
        <div id="upiQrCode"></div>
      </div>
      <div class="qr-amt"><?= fmt_inr($remaining, $sym) ?></div>
      <div class="qr-hint">Open any UPI app &amp; scan — amount is pre-filled</div>
    </div>
    <?php endif; ?>

    <?php if ($companyQR): ?>
    <div style="text-align:center;margin-top:14px">
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);margin-bottom:6px">Or use saved QR</div>
      <img src="<?= htmlspecialchars($companyQR) ?>" alt="QR Code" style="width:130px;height:130px;border-radius:10px;border:1px solid var(--border)">
    </div>
    <?php endif; ?>

    <!-- Feature 5: Partial amount input -->
    <?php if ($remaining > 0.01): ?>
    <div class="partial-pay-box">
      <label data-t="Pay a different amount"><i class="fas fa-rupee-sign"></i> Pay a different amount</label>
      <div class="partial-amt-row">
        <input type="number" id="partialAmt" class="partial-amt-input"
          value="<?= number_format($remaining, 2, '.', '') ?>"
          min="1" max="<?= number_format($remaining, 2, '.', '') ?>"
          placeholder="Enter amount">
        <button class="partial-upi-btn" onclick="payPartial()">
          <i class="fas fa-qrcode"></i> Pay via UPI
        </button>
      </div>
    </div>
    <?php endif; ?>

    <!-- Feature 3: I've Paid button -->
    <?php
      $waNum = preg_replace('/\D/', '', $companyPhone);
      if (strlen($waNum) === 10) $waNum = '91' . $waNum;
      $ivePaidMsg = urlencode('Hi ' . $companyName . '! 👋 I have made the payment for ' . ($isEstimate ? 'Estimate' : 'Invoice') . ' *' . ($inv['invoice_number'] ?? '') . '* of *' . fmt_inr($remaining > 0 ? $remaining : $totalAmt, $sym) . '*. Please confirm receipt. Thank you!');
    ?>
    <a href="https://wa.me/<?= $waNum ?>?text=<?= $ivePaidMsg ?>" class="ive-paid-btn" target="_blank">
      <i class="fab fa-whatsapp" style="font-size:16px"></i> I've Paid — Notify <?= htmlspecialchars($companyName) ?>
    </a>
  </div>
</div>
<?php endif; ?>

<script>
// Generate dynamic UPI QR — only for Pending / Overdue / Partial
<?php if (in_array($inv['status'] ?? '', ['Pending', 'Overdue', 'Partial'])): ?>
(function() {
  var upiString = <?= json_encode($upiBase) ?>;
  function renderQR() {
    var el = document.getElementById('upiQrCode');
    if (!el || typeof QRCode === 'undefined') return;
    new QRCode(el, {
      text       : upiString,
      width      : 160,
      height     : 160,
      colorDark  : '#00695C',
      colorLight : '#ffffff',
      correctLevel: QRCode.CorrectLevel.M
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderQR);
  } else {
    renderQR();
  }
})();
<?php endif; ?>
</script>

<!-- Thank You (Paid) / Notes & T&C (others) -->
<?php if (($inv['status'] ?? '') === 'Paid'): ?>
<div class="card" style="border-color:#C8E6C9;background:linear-gradient(135deg,#F1FFF3,#E8F5E9)">
  <div class="card-body" style="text-align:center;padding:32px 24px">
    <div style="font-size:48px;margin-bottom:12px">🎉</div>
    <div style="font-size:20px;font-weight:800;color:var(--green);margin-bottom:8px">Thank You!</div>
    <div style="font-size:13px;color:#2E7D32;font-weight:500;margin-bottom:6px">
      Payment received for invoice <strong><?= htmlspecialchars($inv['invoice_number'] ?? '') ?></strong>
    </div>
    <div style="font-size:12px;color:var(--muted);line-height:1.7;max-width:320px;margin:0 auto">
      We truly appreciate your prompt payment and your trust in <strong><?= htmlspecialchars($companyName) ?></strong>. Looking forward to serving you again!
    </div>
    <?php if ($companyPhone): ?>
    <?php $waPhone = preg_replace('/\D/','',$companyPhone); if(strlen($waPhone)===10) $waPhone='91'.$waPhone; ?>
    <a href="https://wa.me/<?= $waPhone ?>?text=<?= urlencode('Hi '.$companyName.', thank you for the service!') ?>" target="_blank"
       style="display:inline-flex;align-items:center;gap:6px;margin-top:18px;padding:9px 20px;background:#25D366;color:#fff;border-radius:24px;font-size:12px;font-weight:700;text-decoration:none">
      <i class="fab fa-whatsapp" style="font-size:15px"></i> Say Hi on WhatsApp
    </a>
    <?php endif; ?>
  </div>
</div>
<?php elseif (!empty($inv['notes']) || !empty($inv['terms']) || !empty($inv['bank_details'])): ?>
<div class="card">
  <div class="card-head"><i class="fas fa-sticky-note"></i> <span data-t="Notes &amp; Terms">Notes &amp; Terms</span></div>
  <div class="card-body" style="display:flex;flex-direction:column;gap:14px">
    <?php if (!empty($inv['notes'])): ?>
    <div>
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);margin-bottom:5px" data-t="Notes">Notes</div>
      <div style="font-size:13px;line-height:1.6"><?= nl2br(htmlspecialchars($inv['notes'])) ?></div>
    </div>
    <?php endif; ?>
    <?php if (!empty($inv['bank_details'])): ?>
    <div>
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);margin-bottom:5px" data-t="Bank Details">Bank Details</div>
      <div style="font-size:13px;line-height:1.6;font-family:var(--mono)"><?= nl2br(htmlspecialchars($inv['bank_details'])) ?></div>
    </div>
    <?php endif; ?>
    <?php if (!empty($inv['terms'])): ?>
    <div>
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);margin-bottom:5px" data-t="Terms & Conditions">Terms &amp; Conditions</div>
      <div style="font-size:12px;color:var(--muted);line-height:1.7"><?= nl2br(htmlspecialchars($inv['terms'])) ?></div>
    </div>
    <?php endif; ?>
  </div>
</div>
<?php endif; ?>

<!-- Company footer -->
<div class="card">
  <div class="card-head"><i class="fas fa-building"></i> <span data-t="Issued By">Issued By</span></div>
  <div class="card-body">
    <div class="info-grid">
      <div class="info-item"><label data-t="Company">Company</label><span class="val"><?= htmlspecialchars($companyName) ?></span></div>
      <?php if ($companyGST): ?><div class="info-item"><label data-t="GSTIN">GSTIN</label><span class="val" style="font-family:var(--mono)"><?= htmlspecialchars($companyGST) ?></span></div><?php endif; ?>
      <?php if ($companyPhone): ?><div class="info-item"><label>Phone</label><span class="val"><?= htmlspecialchars($companyPhone) ?></span></div><?php endif; ?>
      <?php if ($companyEmail): ?><div class="info-item"><label>Email</label><span class="val"><?= htmlspecialchars($companyEmail) ?></span></div><?php endif; ?>
      <?php if ($companyAddress): ?><div class="info-item" style="grid-column:1/-1"><label>Address</label><span class="val" style="font-weight:400"><?= nl2br(htmlspecialchars($companyAddress)) ?></span></div><?php endif; ?>
    </div>
    <?php if ($companyPhone): ?>
    <?php $waPhone = preg_replace('/\D/','',$companyPhone); if(strlen($waPhone)===10) $waPhone='91'.$waPhone; ?>
    <a href="https://wa.me/<?= $waPhone ?>?text=<?= urlencode('Hi, I have a query regarding '.($isEstimate?'Estimate':'Invoice').' '.$inv['invoice_number']) ?>" class="wa-contact-btn" target="_blank">
      <i class="fab fa-whatsapp" style="font-size:16px"></i> <span data-t="Chat with us on WhatsApp">Chat with us on WhatsApp</span>
      <?php if (($inv['status'] ?? '') === 'Overdue'): ?><span class="wa-dot"></span><?php endif; ?>
    </a>
    <?php endif; ?>
    <button class="pdf-btn" onclick="window.print()">
      <i class="fas fa-print"></i> Print <?= $isEstimate ? 'Estimate' : 'Invoice' ?>
    </button>
    <button class="pdf-dl-btn" onclick="downloadPDF()">
      <i class="fas fa-file-pdf"></i> Download as PDF
    </button>
  </div>
</div>

<div class="footer" id="footerText">
  <div>This is a secure, read-only view of your <?= $isEstimate ? 'estimate' : 'invoice' ?>.</div>
  <div>Generated by <strong><?= htmlspecialchars($companyName) ?></strong> · Powered by OPTMS Invoice Manager</div>
</div>

<!-- Feature 8: Language toggle -->
<div class="lang-toggle">
  <button class="lang-btn active" onclick="setLang('en')" id="btn-en">EN</button>
  <button class="lang-btn" onclick="setLang('hi')" id="btn-hi">हिंदी</button>
</div>

<?php endif; ?>
</div>

<script>
// ── Sticky bar on scroll ──────────────────────────────────────
(function(){
  const bar = document.getElementById('stickyBar');
  const hdr = document.querySelector('.portal-header');
  if (!bar || !hdr) return;
  const obs = new IntersectionObserver(([e]) => {
    bar.classList.toggle('show', !e.isIntersecting);
  }, {threshold: 0});
  obs.observe(hdr);
})();

// ── Copy UPI ID ───────────────────────────────────────────────
function copyUPI() {
  const id  = document.getElementById('upiId')?.textContent?.trim();
  const btn = document.getElementById('copyBtn');
  if (!id) return;
  const done = () => {
    if (btn) { btn.innerHTML='<i class="fas fa-check"></i> Copied!'; btn.style.background='#388E3C'; }
    setTimeout(()=>{ if(btn){btn.innerHTML='<i class="fas fa-copy"></i> Copy';btn.style.background='';} }, 2000);
  };
  if (navigator.clipboard) {
    navigator.clipboard.writeText(id).then(done).catch(()=>fallback(id,done));
  } else { fallback(id,done); }
}
function fallback(text,cb) {
  const ta=document.createElement('textarea'); ta.value=text; ta.style.position='fixed'; ta.style.opacity='0';
  document.body.appendChild(ta); ta.focus(); ta.select(); try{document.execCommand('copy');}catch(e){}
  document.body.removeChild(ta); cb();
}

// ── Download PDF ───────────────────────────────────────────────
function downloadPDF() {
  const origTitle = document.title;
  document.title = <?= json_encode(($isEstimate ? 'Estimate' : 'Invoice') . '-' . ($inv['invoice_number'] ?? 'doc')) ?>;
  window.print();
  setTimeout(() => { document.title = origTitle; }, 1000);
}

// QR rendering handled above

<?php if ($isEstimate): ?>
// ── Feature 2: Estimate approve/reject with feedback toast ────
document.querySelectorAll('.btn-approve,.btn-reject').forEach(btn => {
  btn.addEventListener('click', function() {
    const isApprove = this.classList.contains('btn-approve');
    // Show confirmation toast
    const toast = document.createElement('div');
    toast.style.cssText = 'position:fixed;bottom:80px;left:50%;transform:translateX(-50%);background:'+(isApprove?'#2E7D32':'#3949AB')+';color:#fff;padding:12px 24px;border-radius:24px;font-size:13px;font-weight:700;z-index:999;box-shadow:0 4px 16px rgba(0,0,0,.25);transition:opacity .4s;text-align:center;max-width:90vw';
    toast.innerHTML = isApprove
      ? '<i class="fas fa-check-circle"></i> ✅ Opening WhatsApp to approve…<br><small style="font-weight:400;opacity:.85">Your approval will be sent to ' + <?= json_encode($companyName) ?> + '</small>'
      : '<i class="fas fa-comment-dots"></i> 💬 Opening WhatsApp for feedback…';
    document.body.appendChild(toast);
    setTimeout(() => { toast.style.opacity='0'; setTimeout(()=>toast.remove(),400); }, 3000);
  });
});
<?php endif; ?>

// ── Feature 5: Partial payment UPI link ──────────────────────
function payPartial() {
  const amt  = parseFloat(document.getElementById('partialAmt')?.value || 0);
  const upi  = <?= json_encode($companyUPI) ?>;
  const name = <?= json_encode($companyName) ?>;
  if (!amt || amt <= 0) { alert('Please enter a valid amount'); return; }
  if (!upi) { alert('UPI ID not configured'); return; }
  const upiLink = 'upi://pay?pa=' + encodeURIComponent(upi) + '&pn=' + encodeURIComponent(name) + '&am=' + amt.toFixed(2) + '&cu=INR';
  window.location.href = upiLink;
}

// ── Feature 8: Hindi / English toggle ────────────────────────
const HINDI = {
  'Invoice Total':      'चालान राशि',
  'Amount Paid':        'भुगतान राशि',
  'Balance Due':        'शेष राशि',
  'Invoice Timeline':   'चालान समयरेखा',
  'Issued':             'जारी',
  'Viewed':             'देखा गया',
  'Paid':               'भुगतान',
  'Pending':            'लंबित',
  'Overdue':            'अतिदेय',
  'Issued By':          'जारीकर्ता',
  'Company':            'कंपनी',
  'Phone':              'फोन',
  'Email':              'ईमेल',
  'Address':            'पता',
  'Notes & Terms':      'नोट्स और शर्तें',
  'Notes':              'नोट्स',
  'Bank Details':       'बैंक विवरण',
  'Terms & Conditions': 'नियम और शर्तें',
  'Pay Now':            'अभी भुगतान करें',
  'Scan to Pay':        'स्कैन करें',
  'Chat with us on WhatsApp': 'WhatsApp पर बात करें',
  'Thank You!':         'धन्यवाद!',
  'Description':        'विवरण',
  'Qty':                'मात्रा',
  'Rate':               'दर',
  'Amount':             'राशि',
  'Total':              'कुल',
  'Subtotal':           'उप-कुल',
  'Discount':           'छूट',
  'GST':                'जीएसटी',
  'Grand Total':        'कुल योग',
  "I've Paid — Notify": 'मैंने भुगतान किया — सूचित करें',
  'Pay a different amount': 'अलग राशि का भुगतान करें',
};

// Store original text for EN restore
const _origText = new Map();

let _currentLang = 'en';
function setLang(lang) {
  if (lang === _currentLang) return;
  _currentLang = lang;
  document.getElementById('btn-en').classList.toggle('active', lang === 'en');
  document.getElementById('btn-hi').classList.toggle('active', lang === 'hi');

  // Translate every element that has data-t attribute
  document.querySelectorAll('[data-t]').forEach(el => {
    const key = el.dataset.t;
    if (!key) return;

    // On first translation, save original text (excluding child elements)
    if (!_origText.has(el)) {
      // Save the text node content only (not innerHTML to preserve icons)
      const textNode = [...el.childNodes].find(n => n.nodeType === 3 && n.textContent.trim());
      _origText.set(el, textNode ? textNode.textContent : el.textContent);
    }

    if (lang === 'hi') {
      const hi = HINDI[key];
      if (hi) {
        // Replace text node only, preserve any child elements (icons etc)
        const textNode = [...el.childNodes].find(n => n.nodeType === 3 && n.textContent.trim());
        if (textNode) {
          textNode.textContent = ' ' + hi;
        } else {
          el.textContent = hi;
        }
      }
    } else {
      // Restore original
      const orig = _origText.get(el);
      if (orig) {
        const textNode = [...el.childNodes].find(n => n.nodeType === 3);
        if (textNode) {
          textNode.textContent = ' ' + orig.trim();
        } else {
          el.textContent = orig;
        }
      }
    }
  });

  // Also translate table headers (th) using their text content as key
  document.querySelectorAll('th').forEach(el => {
    const key = el.textContent.trim();
    if (!_origText.has(el)) _origText.set(el, key);
    if (lang === 'hi' && HINDI[key]) el.textContent = HINDI[key];
    else if (lang === 'en') el.textContent = _origText.get(el) || key;
  });

  if (lang === 'hi') {
    document.title = document.title.replace('Invoice', 'चालान').replace('Estimate', 'अनुमान');
  } else {
    document.title = document.title.replace('चालान', 'Invoice').replace('अनुमान', 'Estimate');
  }
}

// ── Feature 9: Page load animations (run ONCE, remove after done) ──
document.addEventListener('DOMContentLoaded', () => {
  const cards = document.querySelectorAll('.card');
  cards.forEach((card, i) => {
    setTimeout(() => {
      card.classList.add('anim-done'); // fade in via CSS transition
    }, 60 + i * 60);
  });
  // Animate banners once
  const banner = document.querySelector('.estimate-banner, .overdue-banner');
  if (banner) {
    banner.style.opacity = '0';
    setTimeout(() => {
      banner.style.transition = 'opacity .4s ease, transform .4s ease';
      banner.style.opacity = '1';
    }, 80);
  }
});
</script>
</body>
</html>